### ISSUE TITLE
IoT-Spot : Servo Motor Rotation using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#10]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how servo motor is rotated using degrees

Sub Repo : Arduino Scripts

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0), tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'SWOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by ahananupam33** [comment]
Hello, could you assign this issue to me? My SWOC participant ID is 63 as per the sheet

**Comment by prathimacode-hub** [comment]
> Hello, could you assign this issue to me? My SWOC participant ID is 63 as per the sheet

Also share the other details needed to assign the issue. @ahananupam33

**Comment by ahananupam33** [comment]
Tool/Application: Tinkercad
Language: Embedded C
Approach: I will be using a potentiometer to rotate the servo motor (Also I was thinking about adding an LED whose brightness would indicate the angle rotated)

**Comment by prathimacode-hub** [comment]
Awesome, issue assigned to @ahananupam33

**Comment by ahananupam33** [comment]
Thank you
Just a doubt though, we have to add our github id in that participant sheet, right?

**Comment by prathimacode-hub** [comment]
> Thank you Just a doubt though, we have to add our github id in that participant sheet, right?

Yes, right you have to add it on your parallel column using comment option. @ahananupam33

**Comment by ahananupam33** [comment]
Ok, got it
