### ISSUE TITLE
Update Lets Connect button

### ISSUE THREAD

**Issue by Sreemoyee26** [prathimacode-hub/IoT-Spot#102]
---
Title: Update Lets Connect Button
About: Lets Connect button font color is mixed with the background
Name: Sreemoyee Sadhukhan
Label: Feature Request
---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Lets Connect Button font is mixed with its bg color is not visible properly

**Describe the solution you'd like...**

Changing the Lets Connect font color so that it is visible in its bg

**Screenshot

![Screenshot (657)](https://user-images.githubusercontent.com/77785024/156999353-9018069b-9a92-4e6c-a084-7d7a4508c499.png)

**Comment by prathimacode-hub** [comment]
You can make it more valid by adding something more to this issue. This seems less as we have only 3 levels. @Sreemoyee26
