### ISSUE TITLE
 Safe Locker Circuit Simulation on Tinkercad

### ISSUE THREAD

**Issue by rk18venom** [prathimacode-hub/IoT-Spot#103]
---
Title: Safe Locker Circuit Simulation on Tinkercad #103 
About: This is a safe locker circuit in which a person has to set the password using a potentiometer and password set button and after that, a person can recheck the password changing potentiometer value if the password matches then the green light will glow and the servo motor will rotate such that safe lock is open and if it is wrong buzzer nad red light will glow.
Name: Rahul Kashyap
Label: New Project
Assignee: rk18venom

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

I am using TinkerCad for making the circuit in which I am using motor Servo Motor, Arduino UNO R3, 4 Potentiometer, a breadboard, a buzzer, and an RGB led.
This is a safe locker circuit in which a person has to set the password using a potentiometer and password set button and after that, a person can recheck the password changing potentiometer value if password matches then the green light will glow and the servo motor will rotate such that safe lock is open and if it is wrong buzzer nad red light will glow.
**Additional context**
@prathimacode-hub mam, I have already made this circuit simulation and I hope that you will like it.

**Comment by prathimacode-hub** [comment]
Issue assigned to @rk18venom
