### ISSUE TITLE
Arduino Analog Input

### ISSUE THREAD

**Issue by XZANATOL** [prathimacode-hub/IoT-Spot#105]
## Idea

Arduino script that takes Analog input from a potentionmeter and use its value as a delay for blinking intervals of a LED Lamp.

## Benefits

The script will demonstrate who one can make use of an Analog input into Arduino.

Issue made under GSSoC'22 contributions

**Comment by prathimacode-hub** [comment]
I think this is already done. @XZANATOL

**Comment by prathimacode-hub** [comment]
I think this is already done. @XZANATOL
