### ISSUE TITLE
Arduino Light Sensor

### ISSUE THREAD

**Issue by XZANATOL** [prathimacode-hub/IoT-Spot#106]
## Idea

Add a Light Detector Arduino design that visualize the capabilities of LDR component by changing the light intensity of a LED lamp.

## Benifits

* Show the capabilities of a LDR component
* Explain the usage of `analogWrite()` method

**Comment by prathimacode-hub** [comment]
I think this is done too. @XZANATOL

**Comment by prathimacode-hub** [comment]
I think this is done too. @XZANATOL
