### ISSUE TITLE
Fire Alarm System using Arduino

### ISSUE THREAD

**Issue by SiddhantPawar03** [prathimacode-hub/IoT-Spot#110]
---
Title: Fire Alarm System using Arduino
About: I would use Gas Sensor take analog values for same, put some conditions for gas sensor and would produce alert for same
Name: Siddhant Pawar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
Yes, the problem is very much necessary in day to day life as fire alarm system should be pretty efficient to avoid any issues.

**Describe the solution you'd like...**
 I would take up a Gas Sensor take analog values for same, initialize buzzer, led, etc. put some conditions for gas sensor and would produce alert for same.

**Describe alternatives you've considered?**
NA

**Comment by prathimacode-hub** [comment]
Instead use flame sensor since this is about fire alarm systems. Issue assigned to @SiddhantPawar03
