### ISSUE TITLE
Electronic Voting Machine Using Arduino

### ISSUE THREAD

**Issue by vaishnavighiradkar** [prathimacode-hub/IoT-Spot#111]
---
Title: Electronic Voting Machine Using Arduino (EVM)
About: I'll be using push buttons for voting and LCD screen for displaying result.
Name: Vaishnavighiradkar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Describe the solution you'd like...**
I'll be using 5 push buttons for voting and result. and LCD screen for displaying result. 

**Approach to be followed (optional):**
There will be 4 push buttons for voting. A voter can click any one amongst them. The vote count will be displayed on the screen under candidate name. When we push on result button, the result of election will be displayed on screen.

file location: Minor scripts/Arduino

**Comment by prathimacode-hub** [comment]
Issue assigned to @vaishnavighiradkar
