### ISSUE TITLE
Add Favicon 

### ISSUE THREAD

**Issue by Ashish4321-hub** [prathimacode-hub/IoT-Spot#117]
I am gssoc2022 contributor and i want to  work on it.

**Comment by prathimacode-hub** [comment]
Use issue template and kindly elaborate the issue. @Ashish4321-hub

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.

**Comment by muskan467** [comment]
---
Title: IoT-Spot Website
About: Adding a Favicon on tab of website
Name: Muskan Ali Qureshi
Label: Feature Request
Assignee: ''

---

Define You:

- [x] SSOC Participant 
- [ ] Contributor




**Is your feature request related to a problem? Please describe.**


Website tab icon is missing

**Describe the solution you'd like...**


I will add favicon icon to the website.

**Additional context**


![Screenshot (35)](https://user-images.githubusercontent.com/65494453/191761843-5382de8f-4006-4890-b9a7-20d74a48f36a.png)

@prathimacode-hub Please assign.

**Comment by muskan467** [comment]
@mdnazisharman2803 please assign this to me

**Comment by mdnazisharman2803** [comment]
@muskan467 you've been assigned
