### ISSUE TITLE
Simple Claculator using 8051

### ISSUE THREAD

**Issue by nitishkumar07** [prathimacode-hub/IoT-Spot#118]
Title: Simple Claculator using 8051 
About: calculator using 8051 , lcd and keypad
Name: Nitishkumar J G
Label: 
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
   yes . it helps in calculating simple calculation.

**Describe the solution you'd like...**
this project helps in learning to display using lcd.
use 8051 microcontroller,keypad and lcd display for input and output

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned to @nitishkumar07
