### ISSUE TITLE
IoT Spot : Properties Validation of Thermistors

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#12]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to validate the properties of thermistors

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by shreya024** [comment]
@prathimacode-hub I would like to work on this issue, I am a contributor of GSSOC'22.
Tool/application= tikercad
language= embeded C
Approach= I will use a TMP36 Temperature Sensor and control the temperature and register the output with three resistors and LEDs to show the properties of a thermistor using Arduino.

**Comment by prathimacode-hub** [comment]
Issue assigned to @shreya024. All the best.

**Comment by shreya024** [comment]
> Issue assigned to @shreya024. All the best.

Thank you,is it okay if I use LCD display to show the changing resistance instead of LEDs?
