### ISSUE TITLE
Portable Weight Limit Checker using Arduino

### ISSUE THREAD

**Issue by shreya024** [prathimacode-hub/IoT-Spot#121]
Title: Portable Weight Limit Checker using Arduino
About: I'll be using force sensor for detecting weight and a buzzer to indicate when it exceeds threshold. 
Name: Shreya Ghosh
Label: Feature Request 
Assignee: ''

 Define You:

 * [x]  GSSOC Participant
 * []  Contributor

 **Describe the solution you'd like...** I'll be using force sensor for detecting weight and a buzzer to indicate when it exceeds threshold.

file location: Minor scripts/Arduino

**Comment by shreya024** [comment]
@prathimacode-hub Kindly assign this issue to me.

**Comment by prathimacode-hub** [comment]
Issue assigned @shreya024
