### ISSUE TITLE
Improvement of Buttons working

### ISSUE THREAD

**Issue by YalfamIamShaon** [prathimacode-hub/IoT-Spot#122]
Hello, @prathimacode-hub, I have been going through this website and noticed one thing. which is whenever I click on the "Projects" button, it takes me to the "Let's Connect" section. Other buttons are working fine. But the project button is not. So, as a GSSOC22 contributor, I want you to give me this opportunity to work on this issue.
as you can see here
![Capture](https://user-images.githubusercontent.com/84259582/158007140-839813f6-38dc-4d0f-acf0-dac9958e7158.PNG)

**Comment by prathimacode-hub** [comment]
Sure, can you create a layout and add the links of the projects? @YalfamIamShaon

**Comment by YalfamIamShaon** [comment]
Sure @prathimacode-hub , I can do that.

**Comment by prathimacode-hub** [comment]
Ok, proceed. Issue assigned @YalfamIamShaon

**Comment by prathimacode-hub** [comment]
Ok, proceed. Issue assigned @YalfamIamShaon

**Comment by prathimacode-hub** [comment]
Kindly add the issue template to recognize you as GSSoC contributor along with mentioned details. @YalfamIamShaon

**Comment by prathimacode-hub** [comment]
Kindly add the issue template to recognize you as GSSoC contributor along with mentioned details. @YalfamIamShaon

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub  I am a GSSoC'22 contributor. It's been 8 days since this issue was created and assigned. I solved my previous issue and it's PR is under review. I would like to work on this issue. I will add the issue template once it is assigned. Can you assign this issue to me?

**Comment by prathimacode-hub** [comment]
@vaishnavighiradkar, do you want to take this up?

**Comment by vaishnavighiradkar** [comment]
Sorry ma'am, I won't be able to solve this issue. I will create another issue. @prathimacode-hub .

**Comment by Rishita489** [comment]
Hey @prathimacode-hub , I am a GSSOC'22 Contributor . Can you please assign this issue to me . I have solved the issue and send the PR request .

**Comment by prathimacode-hub** [comment]
This is over @Rishita489
