### ISSUE TITLE
Feature : Adding Dynamic counter

### ISSUE THREAD

**Issue by TG922** [prathimacode-hub/IoT-Spot#123]
**Project title**
Adding Dynamic Counter

**Project Description**
This feature will help increase UI of the website.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

![Image3](https://user-images.githubusercontent.com/70098839/158016639-15533266-d101-442c-a19e-5ed6771bdb96.PNG)

**Comment by prathimacode-hub** [comment]
Is dynamic counter needed for this website? @TG922

**Comment by TG922** [comment]
> Is dynamic counter needed for this website? @TG922

No @prathimacode-hub , it is not compulsory. It is looking fine, but adding animation to them adds additional effect to it.
This feature will help increase User Interface(UI) of your website.

**Comment by prathimacode-hub** [comment]
Ok go ahead. @TG922

**Comment by prathimacode-hub** [comment]
Ok go ahead. @TG922

**Comment by prathimacode-hub** [comment]
Are you GSSOC contributor? Kindly add the template provided to know you're if so. @TG922

**Comment by prathimacode-hub** [comment]
Are you GSSOC contributor? Kindly add the template provided to know you're if so. @TG922

**Comment by TG922** [comment]
> Are you GSSOC contributor? Kindly add the template provided to know you're if so. @TG922

Title: Adding Dynamic Counter
About:  I'll be using HTML,CSS,JS for making dynamic counter
Name: Tarun Gaur
Label: Feature Request


## Define You:

[x]   GSSOC '22 Participant
[x]  Contributor

**Describe the solution you'd like...** I'll be using HTML,CSS,JS for making dynamic counter effect on page scroll down. This feature will help increase UI of the website.

file location: ./assets/css, ./assets/js,

## Stack:

[x]  Html
[x] CSS
[x]  JavaScript

**Comment by TG922** [comment]
I've almost worked on it will send PR Today
