### ISSUE TITLE
Hover effect in favicon of footer.

### ISSUE THREAD

**Issue by Areebah03** [prathimacode-hub/IoT-Spot#125]
I want to add hover effect in favicon of footer. Please assign it to me @prathimacode-hub ☺

**Comment by prathimacode-hub** [comment]
Include issue template along with details to get it assigned.  @Areebah03

**Comment by Areebah03** [comment]
Title : Hover Effect
About : Favicon in footer has no hover effect.
Name : Areebah03
Label: Feature Request

## Define You:

- [x] GSSOC Participant
- [x] Contributor

## Is your feature request related to a problem? Please describe.
It is just a styling issue in css.

## Describe the solution you'd like.
I would add hover effect in css of favicons.

## Describe alternatives you've considered?

## Approach to be followed (optional):

## Additional context

**Comment by Areebah03** [comment]
@prathimacode-hub I have added issue template along with details.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Areebah03
