### ISSUE TITLE
Improve working of button in home page.

### ISSUE THREAD

**Issue by Areebah03** [prathimacode-hub/IoT-Spot#128]
About and contact button in home page is not working properly. It only woks when we click the text in these button. I want to fix it so please assign it to me.😐

**Comment by footcricket05** [comment]
can this issue be assigned to me ?
i am a contributor

**Comment by prathimacode-hub** [comment]
@Areebah03, can you add details along with issue template to get it assigned. 

Its on FCFS, you can come up with your own issue if you would like to. @footcricket05

**Comment by Areebah03** [comment]
Title : Fixing working of buttons.
About : About and contact button in home page is not working properly. It only woks when we click the text in these button.
Name : Areebah03
Label : Feature Request

## Define You:

- [x] GSSOC Participant
- [x] Contributor

## Is your feature request related to a problem? Please describe.
It is related to adjusting link in html.

## Describe the solution you'd like.
I would fix the link of the button so that when button is clicked it take us to particular section.

## Describe alternatives you've considered?

## Approach to be followed (optional):

## Additional context

**Comment by Areebah03** [comment]
@prathimacode-hub I have added issue template along with details.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Areebah03
