### ISSUE TITLE
IoT-Spot : Visitor counter using Arduino

### ISSUE THREAD

**Issue by vaishnavighiradkar** [prathimacode-hub/IoT-Spot#129]
---
Title: Visitor counter using Arduino
About: Suggest an idea for this project
Name: vaishnavighiradkar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**

We often need a visitor counter at places like mall or even at home for security purpose. This project will help count number of visitor . Also makes sound when someone is visiting.

**Describe the solution you'd like...**

I'll be using ultrasonic sensor to detect the presence. And a piezo for buzzing.

**Approach to be followed (optional):**
I'll consider a fixed perimeter. If anyone enter within the perimeter, ultrasonic sensor will detect the presence and it will be considered as a visit. And piezo will buzz every time someone visits.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vaishnavighiradkar
