### ISSUE TITLE
Stepper motor interfacing using 8051

### ISSUE THREAD

**Issue by nitishkumar07** [prathimacode-hub/IoT-Spot#134]
---
Title: Stepper motor interfacing
About: making stepper motor move clockwise and anti-clockwise
Name: Nitishkumar J G
Label: Feature Request
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
no
stepper motor interfacing

**Describe the solution you'd like...**
Making stepper motor move clockwise and anti clockwise

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned to @nitishkumar07
