### ISSUE TITLE
improving lets connect form

### ISSUE THREAD

**Issue by leesha19** [prathimacode-hub/IoT-Spot#137]
heyi would like to improve the section "lets connect" using html and css . please assign me the task

**Comment by prathimacode-hub** [comment]
Can you use the template given and fill the details so that I could assign it to you @leesha19

**Comment by leesha19** [comment]
> Can you use the template given and fill the details so that I could assign it to you @leesha19 

Can you please check issue #138 and assign it to me so that I can start working

**Comment by prathimacode-hub** [comment]
Why did you close the issue? @leesha19

**Comment by leesha19** [comment]
> Why did you close the issue? @leesha19 

I want to work on #138 coz I found that the nav bar of website has some issue like there always a hover on let's connect I want to improve the styling ....I have closed this issue so kindly check #138

**Comment by prathimacode-hub** [comment]
Issues or PR's shouldn't be closed from contributors end. I'm just letting you know because things get tracked. @leesha19

**Comment by leesha19** [comment]
> Issues or PR's shouldn't be closed from contributors end. I'm just letting you know because things get tracked. @leesha19 

Yah I only opened this issue so thought of working on this later
