### ISSUE TITLE
improving nav- bar 

### ISSUE THREAD

**Issue by leesha19** [prathimacode-hub/IoT-Spot#138]
---
Title: improving nav bar
About: as we can see that there is a hover effect on lets connect i want to improve the styling
Name: leesha19
Label: Feature Request 
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
its just a styling issue in css 

there is hover effect on lets connect in navigation bar i think it can be improved 
**Describe the solution you'd like...**
i would be addig the hover effect in navigation bar on all the button so that it would look good

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

 #140

**Comment by prathimacode-hub** [comment]
Include the issue template and add the details accordingly to assign the issue. @leesha19

**Comment by leesha19** [comment]
> Include the issue template and add the details accordingly to assign the issue. @leesha19

where's the themplate

**Comment by leesha19** [comment]
> Include the issue template and add the details accordingly to assign the issue. @leesha19

done please check it

**Comment by prathimacode-hub** [comment]
Issue assigned to @leesha19
