### ISSUE TITLE
Hover and Tilt effect to Images

### ISSUE THREAD

**Issue by Kumar-laxmi** [prathimacode-hub/IoT-Spot#141]
---
Title: IoT-Spot
About: Hover and Tilt effect to Images
Name: Kumar Laxmikant
Label: Enahancement Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

Yes, I have discussed with Project Admin
**Is your feature request related to a problem? Please describe.**
No, but this request is just an enhancement

**Describe the solution you'd like...**
To enhance the look of images in website, I will use Vanilla-js-tilt library

**Describe alternatives you've considered?**
The alternate solution can be using simple CSS Classes to create such effects

**Approach to be followed (optional):**
First, I will install vanilla-js-tilt Library in the project
And where ever required I will use methods for enhancement

**Additional context**

![image](https://user-images.githubusercontent.com/76027425/159210295-25484bce-8a94-46de-91b5-f408563c25cc.png)

![image](https://user-images.githubusercontent.com/76027425/159210310-c22f3d6a-5fcd-412b-ae5f-f508c83fcd69.png)

![image](https://user-images.githubusercontent.com/76027425/159245597-fd0bd25f-ae6b-45d9-aa7b-3dbc7cf334e5.png)

**Comment by prathimacode-hub** [comment]
Can you elaborate and also use issue template given? @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
I would like you to look into this link :
https://micku7zu.github.io/vanilla-tilt.js/

**Comment by Kumar-laxmi** [comment]
In this there are various cool tilt effects

**Comment by prathimacode-hub** [comment]
Say it textually using issue template provided along with details of issue to get it assigned. @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
So basically the image would tilt slowly as mouse hovers over it.
By doing this the image would have dynamic look rather that static look.

![image](https://user-images.githubusercontent.com/76027425/159245597-fd0bd25f-ae6b-45d9-aa7b-3dbc7cf334e5.png)

Here I have placed my mouse over it and you can see that image tilted accordingly.

**Comment by Kumar-laxmi** [comment]
The tilt axis wouldn't be too much as the one in the image but would be very less.

**Comment by Kumar-laxmi** [comment]
@prathimacode-hub is the idea ok

**Comment by prathimacode-hub** [comment]
Ok got you. But could you use the template given to include these details so that i can assign it to you? @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
> Ok got you. But could you use the template given to include these details so that i can assign it to you? @Kumar-laxmi

@prathimacode-hub I didn't get what what you mean

**Comment by Kumar-laxmi** [comment]
Bro the only thing is it won't effect your template, it is just a minor enhancement

**Comment by prathimacode-hub** [comment]
First of all I am not bro, template is included to add the details regarding the issue and let us know that you are a GSSOC contributor. It has nothing in relevant to changes you make. This is only done to assign you the issue. For reference, here is the template : https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/feature_request.md. You can replace with the details and template using edit option. Always read the README and CONTRIBUTING GUIDELINES before taking up any issue, so that you will be aware of what I meant here. @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
> First of all I am not bro, template is included to add the details regarding the issue and let us know that you are a GSSOC contributor. It has nothing in relevant to changes you make. This is only done to assign you the issue. For reference, here is the template : https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/feature_request.md. You can replace with the details and template using edit option. Always read the README and CONTRIBUTING GUIDELINES before taking up any issue, so that you will be aware of what I meant here. @Kumar-laxmi

Actually I am totally new to Open-Source, that is why I didn't get you what you said earlier

**Comment by prathimacode-hub** [comment]
No worries, it happens. That's how we learn right. Don't worry. I understood. So I indeed shared up the link with you. @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
@prathimacode-hub please have a look I have updated the first comment

**Comment by prathimacode-hub** [comment]
Issue assigned to @Kumar-laxmi
