### ISSUE TITLE
scroll bar

### ISSUE THREAD

**Issue by leesha19** [prathimacode-hub/IoT-Spot#142]
---
Title: scroll bar
About: scroll bar of website is dark 
Name: leesha19
Label: Feature Request 
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
its just a styling issue in css 

the scroll bar of the website is dark in color 
**Describe the solution you'd like...**
i would be changing the scroll bar  so that it would look good and may be more clearly visible

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned to @leesha19

**Comment by dvlsatya** [comment]
can you assign this to me

**Comment by Rishita489** [comment]
Hey @prathimacode-hub , I am a GSSOC'22 Contributor . Can you please assign this issue to me . I have send the PR solving the above issue  . You can review and merge it .

**Comment by leesha19** [comment]
> Hey @prathimacode-hub , I am a GSSOC'22 Contributor . Can you please assign this issue to me . I have send the PR solving the above issue . You can review and mergeit was assigned to me uh can contribute until its assigned to you
