### ISSUE TITLE
Obstacle Avoidance Bot Circuit Simulation on TinkerCad

### ISSUE THREAD

**Issue by rk18venom** [prathimacode-hub/IoT-Spot#143]
---
Title: Obstacle Avoidance Bot Circuit Simulation on TinkerCad #143
About: Making the obstacle avoidance bot using ultrasonic sensor.
Name: Rahul Kashyap
Label: New Project
Assignee: rk18venom

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

I am using TinkerCad for making the circuit in which I am using ultrasonic sensor and Arduino Uno r3 and sensing the distance of the object if it is less than or equal to the threshold we will avoid and take a turn to left else move straight.
**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned to @rk18venom
