### ISSUE TITLE
Emergency-Ventilator

### ISSUE THREAD

**Issue by SiddhantPawar03** [prathimacode-hub/IoT-Spot#144]
---
Title: Emergency Ventilator
About: Creating a ventilator which could be made at home.
Name: Siddhant Pawar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
Yes, the problem arise due to ongoing pandemic of covid-19 as people were not able to cure themselves due to lack of ventilators availability. This project would help to make ventilators using day to day components.

**Describe the solution you'd like...**
I would use arduino uno, potentiometers to check for 'BPM'(Breathes per minute) and 'Volume', will put few conditions along with buzzer to alert for any circumstances.

**Describe alternatives you've considered?**
NA

**Comment by prathimacode-hub** [comment]
Issue assigned to @SiddhantPawar03
