### ISSUE TITLE
Smart street light using Arduino

### ISSUE THREAD

**Issue by nitishkumar07** [prathimacode-hub/IoT-Spot#145]
---
Title: Smart street light 
About: creating smart street light using Arduino, ldr and ir sensor
Name: Nitishkumar J G
Label: Feature Request
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
yes
feature deals with the wastage of electricity by the street lights

**Describe the solution you'd like...**
use ldr to automatically on and off the street light and use ir sensor to ON street light when the street is used.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned to @nitishkumar07
