### ISSUE TITLE
Add footer in blog page

### ISSUE THREAD

**Issue by Riddhi9570** [prathimacode-hub/IoT-Spot#149]
---
About: Add footer in blog page
Name: Riddhi Bhagat
Label: Feature Request

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

No footer is there in blog page.

**Describe the solution you'd like...**

- I will add the footer.
- I will add a smooth transition effect on hovering over the cards in blog page.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Riddhi9570

**Comment by tasneemahmed123** [comment]
my name is tasneem ahmed 
about this issue i will add afooter in blog page  it will add copy right of this website and some transation effects if allow
