### ISSUE TITLE
IoT-Spot : Humidity Sensing using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#15]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to sense the humidity using Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub I'm GSSOC'22 Contributor, I would like to work on same issue.

**Comment by SarthakSKumar** [comment]
Hey there. I am a GSSOC '22 Contributor. Can I please work on this issue?

**Comment by prathimacode-hub** [comment]
@SarthakSKumar, clarity on issue please to be chosen? 

@SiddhantPawar03, expressing interest over issues from today onward will be assigned on FCFS basis.

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub I have recently done my GSSOC'22 first assigned task, further I would like to work on Humidity-Sensing using arduino. Basically I would use arduino uno along with neopixel to detect humidity, would set variety of color conditions and find the solution for the same.
Looking forward to contribute for the issue, Please do assign me task!

**Comment by SarthakSKumar** [comment]
> Issue assigned @SarthakSKumar. All the best.

Thank you for the reply

**Comment by prathimacode-hub** [comment]
Oops, I had to assign this issue to @SiddhantPawar03 instead of @SarthakSKumar on FCFS basis. But somehow I missed it due to same starting letter S. For now, I will accept both the PRs. From next onwards, only 1 can work in a single issue.

**Comment by SarthakSKumar** [comment]
Ok ma'am. Sure. Will keep this in mind. Thank you!
