### ISSUE TITLE
GPS Locater using Arduino

### ISSUE THREAD

**Issue by shreya024** [prathimacode-hub/IoT-Spot#150]
Title: GPS Locater using Arduino
About: I'll be implementing a GPS Locater using Arduino. 
Name: Shreya Ghosh
Label: Feature Request 
Assignee: ''

 Define You:

 * [x]  GSSOC Participant
 * []  Contributor

 **Describe the solution you'd like...** I'll be using two Arduino UNOs,Neopixel,and LED display to implement a GPS Locater.

file location: Minor scripts/Arduino

**Comment by shreya024** [comment]
@prathimacode-hub Kindly assign

**Comment by prathimacode-hub** [comment]
Issue assigned to @shreya024
