### ISSUE TITLE
Improvement in UI of specific sections

### ISSUE THREAD

**Issue by Nitya-S27** [prathimacode-hub/IoT-Spot#152]
- Adding glass morphism and background will make the cards more interactive.
- The social icons are shown twice both in let's connect form and in the footer. A footer that contains the social information as well as the let's connect form will enhance the UI. 
- The website has a scrollbar at the bottom which is adding extra width of the website and is of no use.

The image below shows the issue of extra width.

![Screenshot (410)](https://user-images.githubusercontent.com/81871441/160231726-cd2a0638-0ce3-48e9-8bb5-d344307d54c0.png)

**Comment by prathimacode-hub** [comment]
Are you a GSSOC contributor? Kindly use a issue template provide so that i could assign it. @Nitya-S27

**Comment by Nitya-S27** [comment]
> Are you a GSSOC contributor? Kindly use a issue template provide so that i could assign it. @Nitya-S27

Yes I'm a GSSOC'22 contributor.

**Comment by prathimacode-hub** [comment]
Yes, you can edit it up directly here, replace it with the template and include the details you had provided. @Nitya-S27

**Comment by Nitya-S27** [comment]
About: Improvement in UI of specific sections
Name: Nitya Singh
Label: Feature Request and Bug Report

# **Define You:**

- [x] GSSOC Participant
- [x] Contributor

# **Is your feature request related to a problem? Please describe.**

- [x] New Feature
- [x] Bug Fixes

### Fixes Issue  #152

# **Describe the solution you'd like...**

- Adding glass morphism and background will make the cards more interactive.
- The social icons are shown twice both in let's connect form and in the footer. A footer that contains the social information as well as the let's connect form will enhance the UI.
- The website has a scrollbar at the bottom which is adding extra width of the website and is of no use.

# **Additional Context**

The image below shows the issue of extra width.

![Screenshot (410)](https://user-images.githubusercontent.com/81871441/160483445-c0b14668-44bf-4155-a5b0-d01ddf7de3c9.png)

**Comment by Nitya-S27** [comment]
> Yes, you can edit it up directly here, replace it with the template and include the details you had provided. @Nitya-S27

@prathimacode-hub Done

**Comment by prathimacode-hub** [comment]
Issue assigned to @Nitya-S27

**Comment by Nitya-S27** [comment]
@prathimacode-hub  can you please add GSSOC label to the issue along with the level 0, 1, 2 or 3 label.

**Comment by Nitya-S27** [comment]
@prathimacode-hub Check out the enhanced UI of the footer that includes the forms as well as the social icons.
Suggest changes if any.

![Screenshot (417)](https://user-images.githubusercontent.com/81871441/161427601-e61e3873-fb2b-4a98-b7de-88391e51bc0a.png)

**Comment by prathimacode-hub** [comment]
Looks cool, but i think navigating arrow to should be below the contact form. @Nitya-S27

**Comment by Nitya-S27** [comment]
> Looks cool, but i think navigating arrow to should be below the contact form. @Nitya-S27

Okay I will make PR with the changes.
