### ISSUE TITLE
Automatic Room Temperature Controller 

### ISSUE THREAD

**Issue by rk18venom** [prathimacode-hub/IoT-Spot#155]
---
Title: Automatic Room Temperature Controller #155
About: Making the Automatic Room Temperature Controller.
Name: Rahul Kashyap
Label: New Project
Assignee: rk18venom

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

I am using TinkerCad for making the circuit in which I am using a temperature measuring sensor and many more components using these I am making the circuit for controlling the room temperature.
**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned to @rk18venom
