### ISSUE TITLE
Cursor pointer in Lets connect button

### ISSUE THREAD

**Issue by Areebah03** [prathimacode-hub/IoT-Spot#158]
I want to add cursor pointer in Lets Connect button. Please assign it to me @prathimacode-hub 😊

## Screenshot
![Screenshot 2022-03-29 124212](https://user-images.githubusercontent.com/85051124/160554616-1a28a5a6-0659-4c49-a9a3-0362f2e54f0c.png)

**Comment by prathimacode-hub** [comment]
Could you elaborate? @Areebah03

**Comment by Areebah03** [comment]
When we hover on lets connect button it shows arrow pointer. I want to change it to cursor pointer in lets connect like all other links of navbar. 

![pic1](https://user-images.githubusercontent.com/85051124/162606578-96dbd4bf-1ac8-40a2-8610-b7a5e9d76cd5.jpg)
## I want to add cursor pointer like that of about us link shown above.
![pic2](https://user-images.githubusercontent.com/85051124/162606584-abb949c3-0e12-4210-ae87-a78280f5cdde.jpg)

**Comment by prathimacode-hub** [comment]
Got you. First add the issue template and then include the details to get it assigned.  @Areebah03

**Comment by Areebah03** [comment]
Title : Cursor Pointer
About : I want to add cursor pointer in lets connect button.
Name : Areebah03
Label: Feature Request

## Define You:

- [x] GSSOC Participant
- [x] Contributor

## Is your feature request related to a problem? Please describe.
It is just a styling issue in css.

## Describe the solution you'd like.
I would add cursor pointer in lets connect button.

## Describe alternatives you've considered?

## Approach to be followed (optional):

## Additional context

**Comment by Areebah03** [comment]
@prathimacode-hub I have added the issue template and include the details.

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.
