### ISSUE TITLE
Controlling LED Using IR Remote

### ISSUE THREAD

**Issue by vaishnavighiradkar** [prathimacode-hub/IoT-Spot#160]
---
Title: Controlling LED using IR Remote
About: How to use IR Sensor and IR remote
Name: vaishnavighiradkar
Label: Feature Request
Assignee: ''
Location: Minor scripts/Arduino/Controlling LED Using IR Remote
---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

After this, we'll get to know how an IR sensor and IR remote is used and manipulated

We'll be controlling an LED light using an IR sensor and an IR remote

The LED light should turn on and off after pressing power button on IR remote.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vaishnavighiradkar
