### ISSUE TITLE
Create a Blog Page

### ISSUE THREAD

**Issue by Kumar-laxmi** [prathimacode-hub/IoT-Spot#164]
---
Title: IoT-Spot
About: Create a new themed blog page
Name: Kumar Laxmikant
Label: Feature Request
Assignee: ''"

---

Define You:

- [X] GSSOC Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
Yes since this page might be an important part of the website

**Describe the solution you'd like...**
I will use HTML, CSS (bootstrap) and JS (Possibly Node JS Modules)

**Describe alternatives you've considered?**
This idea can be implemented simply using no framework and modules

**Approach to be followed (optional):**
- I will create HTML File 
- Write the code to achieve the required designed

The template that I would like to follow is:
![image](https://user-images.githubusercontent.com/76027425/160735041-622e840a-0848-49bd-bc59-345a70f3c384.png)

**Additional context**
The Blog Page(currently) : 
![image](https://user-images.githubusercontent.com/76027425/160734776-16a61ffe-af9c-4244-a2cd-96038c923027.png)

**Comment by Kumar-laxmi** [comment]
@prathimacode-hub Please look into this issue

**Comment by prathimacode-hub** [comment]
Issue assigned to @Kumar-laxmi
