### ISSUE TITLE
Ping Pong Game using LCD and Arduino

### ISSUE THREAD

**Issue by SarthakSKumar** [prathimacode-hub/IoT-Spot#167]
---
Title: Ping Pong Game using LCD and Arduino
About: Using LCD, Simulating a Ping Pong Game, which is played using push buttons, with Arduino
Name: Sarthak S Kumar
Label: Feature Request
Assignee: 

---

Define You:

- [x] GSSOC Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
Not related to a problem. It's a new project I wanted to add under the repo.

**Describe the solution you'd like...**
To add a project under the repo which consists of a ping pong game, which will be made using LCD and Arduino.

**Describe alternatives you've considered?**

Not yet. I have worked on the same project beforehand, and have the source for the same.

**Comment by prathimacode-hub** [comment]
Issue assigned to @SarthakSKumar
