### ISSUE TITLE
IoT-Spot : Current Sensing using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#17]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to sense current using Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by SarthakSKumar** [comment]
Hey there. Can you please assign this issue to me? Waiting for your reply

**Comment by prathimacode-hub** [comment]
Choose one out of multiple issues you had expressed interest for? @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> Choose one out of multiple issues you had expressed interest for? @SarthakSKumar

Yes. Sure. I shall go with Displaying Time on LCD. Thanks for you reply

**Comment by prathimacode-hub** [comment]
Ok 👍@SarthakSKumar

**Comment by prathimacode-hub** [comment]
To get assigned to this issue, respond with your tool/application you would like to choose. the programming language and the approach you would follow. @aditisharma001

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by prathimacode-hub** [comment]
Decide on one and give asked details to get it assigned. @sceary-expert

**Comment by vaishnavighiradkar** [comment]
I am willing to work on this issue. I will be using Proteus software for circuit development , arduino IDE  to write code and C++ as programming language.  Please assign this issue to me. @prathimacode-hub

**Comment by rk18venom** [comment]
---
Title: Current Sensing using Arduino #17
About: Sensing the current using Arduino.
Name: Rahul Kashyap
Label: New Project
Assignee: rk18venom

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor




**Is your feature request related to a problem? Please describe.**



**Describe the solution you'd like...**



**Describe alternatives you've considered?**



**Approach to be followed (optional):**


I am using TinkerCad for making the circuit in which I am using an oscilloscope and servo motor where I will show the graph of current and its changing magnitude.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vaishnavighiradkar on FCFS basis.

**Comment by prathimacode-hub** [comment]
@rk18venom, we have many more issues coming up.

**Comment by prathimacode-hub** [comment]
Issue template is needed only when its issues are created on own. @rk18venom

**Comment by prathimacode-hub** [comment]
You can come up with new choice for me to get it assigned. @rk18venom

**Comment by rk18venom** [comment]
ok mam.
