### ISSUE TITLE
Logo in website

### ISSUE THREAD

**Issue by Areebah03** [prathimacode-hub/IoT-Spot#170]
I want to add image logo in website to enhance its UI. Please assign it to me @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Could you elaborate? @Areebah03

**Comment by Areebah03** [comment]
I want to add image logo in navbar to enhance its UI


![img](https://user-images.githubusercontent.com/85051124/162606724-92568141-1a85-4d6e-8a95-2eee9475917b.png)

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.

**Comment by Kritika0035** [comment]
I would like to design the Logo of this Iot-Spot website. Pls assign me this issue.
