### ISSUE TITLE
Hover effect of links in navbar

### ISSUE THREAD

**Issue by Areebah03** [prathimacode-hub/IoT-Spot#171]
I want to improve the hover effect of links in navbar. Please assign it to me @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Elaboration please? @Areebah03

**Comment by Areebah03** [comment]
I want to improve hover effect of links in navbar by adding border-radius, changing background color.


![img2](https://user-images.githubusercontent.com/85051124/162606849-80500c0b-27f1-445b-b83d-dc57ac6063b3.png)
