### ISSUE TITLE
Smart Parking System using Arduino

### ISSUE THREAD

**Issue by SiddhantPawar03** [prathimacode-hub/IoT-Spot#172]
---
Title: Smart Parking System using Arduino
About: Project would guide the vehicles during parking as well as will update the parking count at same time.
Name: Siddhant Pawar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
Yes, the problem is one of the major faced issue as there is requirement of system which would assist the car's at the time of parking vehicle as well as having a real time update of car count in respective parking hub.

**Describe the solution you'd like...**
I would work on Tinkercad simulation, would be using arduino uno along with IR and ultrasonic sensor to keep update and navigate vehicle also would be using LED's and buzzer.

**Describe alternatives you've considered?**
NA

**Comment by prathimacode-hub** [comment]
Issue assigned to @SiddhantPawar03
