### ISSUE TITLE
Mood Ring Light using Arduino

### ISSUE THREAD

**Issue by shreya024** [prathimacode-hub/IoT-Spot#174]
Title: Mood Ring Light using Arduino
About: I'll be implementing a Mood Ring Light/Lamp using Arduino.
Name: Shreya Ghosh
Label: Feature Request
Assignee: ''

Define You:

* [x]  GSSOC Participant
 * []  Contributor

Describe the solution you'd like... I'll be using Arduino UNO,3 Neopixels to implement a Mood Ring Lamp.

file location: Minor scripts/Arduino

**Comment by shreya024** [comment]
@prathimacode-hub Kindly assign

**Comment by prathimacode-hub** [comment]
Issue assigned to @shreya024
