### ISSUE TITLE
Door lock system using 8051 microcontroller About: key

### ISSUE THREAD

**Issue by nitishkumar07** [prathimacode-hub/IoT-Spot#175]
---
Title:door lock system using 8051 microcontroller
About: using lcd,motor driver ICL283D,dc motor,keypad,in Proteus
Name: Nitishkumar J G
Label: Feature Request
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
yes

**Describe the solution you'd like...**
by using lcd,motor driver ICL283D,dc motor,keypad create a door lock system.

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned to @nitishkumar07
