### ISSUE TITLE
Improving Go to top button

### ISSUE THREAD

**Issue by aaryahjolia** [prathimacode-hub/IoT-Spot#177]
The go to top button currently is aligned upwards, but it will look more cool if it got placed in center so I want to add these changes.

Current button : 

![GSSoC](https://user-images.githubusercontent.com/82600388/161589389-77fb8176-59c1-48c1-834f-8167550072a3.png)

**Comment by prathimacode-hub** [comment]
Add an issue template along with mentioned details to get it assigned. @aaryahjolia
