### ISSUE TITLE
IoT-Spot : Voltage Sensing using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#18]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to sense voltage using Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by rittikadeb** [comment]
Hi @prathimacode-hub, I am a GSSOC'22 contributor. I would like to work on this issue.

**Comment by SarthakSKumar** [comment]
Hey there. I am a GSSOC '22 Contributor. Can I please work on this issue?

**Comment by prathimacode-hub** [comment]
@SarthakSKumar You can work on only 1 issue at a time, so choose it wisely

@rittikadeb, contribution starts from today, so participants who express interest would be assigned on FCFS basis

**Comment by SarthakSKumar** [comment]
> @SarthakSKumar You can work on only 1 issue at a time, so choose it wisely
> 
> @rittikadeb, contribution starts from today, so participants who express interest would be assigned on FCFS basis

I shall go with the Project: Displaying Time in LCD. Thanks for the reply

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub I've done my two task for GSSOC'22, further interested to contribute more, I would like to contribute on same issue of measuring voltage using arduino.
I would work on tinkercad simulation, would take analog input voltage value do few computations using known resistors and would display the result for same.
Please do assign me this issue!

**Comment by prathimacode-hub** [comment]
Issue assigned to @SiddhantPawar03
