### ISSUE TITLE
Introduction to 8051 MicroController

### ISSUE THREAD

**Issue by SiddhantPawar03** [prathimacode-hub/IoT-Spot#183]
---
Title: Introduction to 8051 MicroController
About: Creating informational document
Name: Siddhant Pawar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
Yes, the related information regarding the 8051 Microcontroller in necessary it's description, pin diagram, working, etc. will be covered in the following document.

**Describe the solution you'd like...**
The related information will be appended in the document containing all the material.

**Describe alternatives you've considered?**
NA

**Comment by prathimacode-hub** [comment]
Issue assigned to @SiddhantPawar03
