### ISSUE TITLE
Keypad Calculator Using Arduino

### ISSUE THREAD

**Issue by vaishnavighiradkar** [prathimacode-hub/IoT-Spot#184]
---
Title: Calculator Using Arduino
About: Making a calculator using arduino board and other components
Name: vaishnavighiradkar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**

From this feature , we will get to know how to use keypad and build a calculator from it.

**Approach to be followed (optional):**

I'll be using keypad to take input of numbers and after performing simple algebra operations wished by user, result will be displayed on the LCD screen.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vaishnavighiradkar
