### ISSUE TITLE
Add Titles and Content in Blog Section

### ISSUE THREAD

**Issue by Geetanjaligupta123** [prathimacode-hub/IoT-Spot#185]
Hi,
In Blog Section ,I want to add titles and content of titles. Here's the screenshot of the problem
![Screenshot (13)](https://user-images.githubusercontent.com/100347557/162149503-01b1e386-4711-4b14-94d9-12c807ee8f35.png)

**Comment by deekshhaa** [comment]
> Please assign this issue to me

**Comment by prathimacode-hub** [comment]
@geetanjali2001 could you include issue template along with the mentioned details above so that i could assign it to you? 

@deekshhaa, you're on queue. Preference is given @geetanjali2001 on first come first serve
