### ISSUE TITLE
IoT-Spot : LED Activation with Mic in Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#19]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to activate  LED with Mic in Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by rk18venom** [comment]
Hello @prathimacode-hub I am GSSOC 22 contributor, I would like to do this, Can you assign me this issue?

**Comment by prathimacode-hub** [comment]
Absolutely, let me know of the approach and tool you would use to get it assigned. @rk18venom

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by prathimacode-hub** [comment]
Provide the details mentioned to get it assigned. @sceary-expert

**Comment by shreya024** [comment]
@prathimacode-hub I would like to work on this issue, I am a contributor of GSSOC'22.
Tool/application= tinkercad
language= embedded C
Approach= I will use a piezo buzzer as a microphone and using its value to activate the LED using Arduino.

**Comment by prathimacode-hub** [comment]
Issue assigned to @shreya024
