### ISSUE TITLE
Adding a Scroll bar 

### ISSUE THREAD

**Issue by Rhydham2809** [prathimacode-hub/IoT-Spot#191]
---
Title: Adding a Scroll bar
About: Adding a scroll bar in the home page
Name: Rhydham Gundigara
Label: Feature Request
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The scroll bar is missing in the home page

**Describe the solution you'd like...**

I will add a scroll bar in the home page.

**Comment by prathimacode-hub** [comment]
Include an issue template provided and mention the details accordingly to get it assigned. @Rhydham2809

**Comment by Rhydham2809** [comment]
I included the issue template, kindly assign the issue. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned to @Rhydham2809

**Comment by Rhydham2809** [comment]
@prathimacode-hub 
Please suggest which color looks better for the app according to that I will make a final change and then make a pull request
![Screenshot (16)](https://user-images.githubusercontent.com/100224159/163292237-30b1891c-6af5-43da-a88b-48fc402c7ab2.png)
![Screenshot (15)](https://user-images.githubusercontent.com/100224159/163292279-b65987b1-de02-4e2c-94f7-1be3880cdab2.png)

**Comment by prathimacode-hub** [comment]
2nd one is better. @Rhydham2809

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.
