### ISSUE TITLE
Improve Hamburger Menu List

### ISSUE THREAD

**Issue by amitsvg** [prathimacode-hub/IoT-Spot#195]
The website is a little bit zoomed in when opened in mobile, hamburger menu is not clearly visible. User has to zoom-out to see the hamburger-menu. The animation of hamburger menu-icon is very nice . background of side menu is very dark. Background color and button designs can be improved.

![mvvvv](https://user-images.githubusercontent.com/72488615/162767227-a6298bca-422e-42c1-ab31-834679740218.jpg)

I want to work on this issue as GSSOC's 2022 contributor.

**Comment by prathimacode-hub** [comment]
Use issue template and include this issue details to get it assigned. @amitsvg
