### ISSUE TITLE
Dino Game using Arduino

### ISSUE THREAD

**Issue by SarthakSKumar** [prathimacode-hub/IoT-Spot#196]
---
Title: Dino Game using Arduino
About: Using LCD and Pushbuttons, with Arduino
Name: Sarthak S Kumar
Label: Feature Request
Assignee: 

---

Define You:

- [x] GSSOC Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
Not related to a problem. It's a new project I wanted to add under the repo.

**Describe the solution you'd like...**
To add a project under the repo which consists of a Dino Game(Mimicking the Chrome Dino Game), which will be made using Pushbuttons, LCD and Arduino.

**Describe alternatives you've considered?**

None. I shall make sure that my code works to its best, by testing and debugging the code I write.

**Comment by prathimacode-hub** [comment]
Issue assigned to @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Thank you ma'am
