### ISSUE TITLE
Obstacle Avoidance Game using Arduino

### ISSUE THREAD

**Issue by shreya024** [prathimacode-hub/IoT-Spot#199]
Title: Obstacle Avoidance Game using Arduino
About: I'll be implementing the game using LCD and pushbutton 
Name: Shreya Ghosh
Label: Feature Request
Assignee: ''

Define You:

* [x]  GSSOC Participant
 * []  Contributor

Describe the solution you'd like... I'll be using LCD as game screen and pushbutton as controller
file location: Minor scripts/Arduino

**Comment by shreya024** [comment]
@prathimacode-hub Kindly assign

**Comment by prathimacode-hub** [comment]
Issue assigned to @shreya024
