### ISSUE TITLE
Controlling DC Motor Using IR Remote

### ISSUE THREAD

**Issue by vaishnavighiradkar** [prathimacode-hub/IoT-Spot#200]
---
Title: Controlling DC Motor Using IR Remote
About: Changing direction of DC Motor using IR remote
Name: vaishnavighiradkar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**

We'll learn how to use IR remote to control and change the direction DC Motor

**Describe the solution you'd like...**

When the next(>>|) button on IR remote is pressed, the DC motor will rotate in clockwise direction and when previous(|<<) button is pressed on the IR remote, the DC motor will rotate in anti-clockwise direction

**Approach to be followed (optional):**

I'll be using IR sensor to detect input from IR remote. And according to that input, DC motor will change it's direction.

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub Please assign this issue to me.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vaishnavighiradkar
