### ISSUE TITLE
Hover effect in favicons

### ISSUE THREAD

**Issue by Areebah03** [prathimacode-hub/IoT-Spot#203]
I want to add hover effects in favicon in footer section. Please assign it to me @prathimacode-hub

![ss1](https://user-images.githubusercontent.com/85051124/163533095-545d29dd-e9e6-4ce4-8f2e-f4de12ffce4b.png)

**Comment by Areebah03** [comment]
@prathimacode-hub Please assign.

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.

**Comment by ShravaniAK** [comment]
can i work on this

**Comment by prathimacode-hub** [comment]
You can create a new issue, since it's initiated by other and get it assigned. @ShravaniAK

**Comment by its-abhishek** [comment]
I would like work on this issue

**Comment by prathimacode-hub** [comment]
This issue is not necessary now. You can express interest on other issues or come up with a new one. @its-abhishek
