### ISSUE TITLE
Improve working of button

### ISSUE THREAD

**Issue by Areebah03** [prathimacode-hub/IoT-Spot#204]
Title : Improve working of buttons and add hover effect in favicon of footer
About : About and contact button in home page is not working properly. It only works when we click the text in these button.
I want to improve it. I also want to add hover effects in favicon of footer
Name : Areebah03
Label : Feature Request

## Define You:

- [x] GSSOC Participant
- [x] Contributor

## Is your feature request related to a problem? Please describe.
It is related to adjusting link in html and adding css property

## Describe the solution you'd like.
I would fix the link of the button so that when button is clicked it take us to particular section. And I will add hover effects in favicon of footer.

## Screenshots
![ss2](https://user-images.githubusercontent.com/85051124/163533506-1d5eacea-3a43-460c-a58f-b791ac053cd6.png)

![ss1](https://user-images.githubusercontent.com/85051124/163533095-545d29dd-e9e6-4ce4-8f2e-f4de12ffce4b.png)

**Comment by Areebah03** [comment]
@prathimacode-hub Please assign

**Comment by prathimacode-hub** [comment]
We have been instructed to not assign basic issues. You can add something to this to make it eligible to be considered for GSSoC. @Areebah03

**Comment by Areebah03** [comment]
@prathimacode-hub I will improve working of button and add hover effects in favicon of footer

**Comment by prathimacode-hub** [comment]
Ok, can you modify the context above so that I could assign it to you? @Areebah03

**Comment by Areebah03** [comment]
@prathimacode-hub  I have modified the issue accordingly.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Areebah03
