### ISSUE TITLE
Pedestrian Traffic Signal System Using Arduino

### ISSUE THREAD

**Issue by SarthakSKumar** [prathimacode-hub/IoT-Spot#206]
---
Title: Traffic Signal System Using Arduino
About: Using LED's and Pushbutton, with Arduino
Name: Sarthak S Kumar
Label: Feature Request
Assignee: 

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
Not related to a problem. It's a new project I wanted to add under the repo.

**Describe the solution you'd like...**
To add a project under the repo which consists of a Pedestrian Traffic Signal System, which will be made Using LED's and Pushbutton, with Arduino

**Describe alternatives you've considered?**

None. I shall make sure that my code works to its best, by testing and debugging the code I write.

**Comment by prathimacode-hub** [comment]
Issue assigned to @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Thank you ma'am @prathimacode-hub
