### ISSUE TITLE
Io-Spot : Record Frequency to SD Card using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#21]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to record frequency to SD Card using Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by prathimacode-hub** [comment]
Choose 1 issue and let me know along with mentioned details asked to get it assigned. You can work on only 1 issue at a time. @sceary-expert

**Comment by SiddhantPawar03** [comment]
Hey, is anyone still working on same issue?

**Comment by prathimacode-hub** [comment]
No one @SiddhantPawar03. If you're interested I could assign it to you.

**Comment by SiddhantPawar03** [comment]
> No one @SiddhantPawar03. If you're interested I could assign it to you.

Yes! I would like to work on same issue @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Ok issue assigned to @SiddhantPawar03
