### ISSUE TITLE
Let's Connect section not linked

### ISSUE THREAD

**Issue by BabyElias** [prathimacode-hub/IoT-Spot#210]
On clicking on Let's Connect, the website instead of taking to the Let's Connect part at the end of the page directly opens the email app (& also, the projects link is linked to the Let's connect section of the website which in my opinion is inappropriate.)

I would like to take up this issue under GSSoC'22.

**Comment by prathimacode-hub** [comment]
What's your approach? @BabyElias

**Comment by BabyElias** [comment]
![nrt](https://user-images.githubusercontent.com/95405559/165047549-9af90492-a318-4fd7-92dc-76876971edb5.JPG)
The Let's connect link should be linked directly to the Let's connect section( and the mail tab in there should open to the mail app, as already available).
There can be a separate Projects section on the same page or maybe a new webpage can be created for Projects tab.

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.

**Comment by Harsh3363** [comment]
Can i fix this?

**Comment by prathimacode-hub** [comment]
@Harsh3363 @SHRUTI-SINGH16 The core of issue is not sufficient to validate as a PR. You can come up with new issue else you can add something more to it for being considered as level 1 issue.
