### ISSUE TITLE
Node MCU wireless communication for Traffic Signal Control

### ISSUE THREAD

**Issue by SiddhantPawar03** [prathimacode-hub/IoT-Spot#216]
---
Title: Node MCU wireless communication for Traffic Signal Control
About: Would be using Node MCU for wireless communication of traffic signal control
Name: Siddhant Pawar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
Yes, as demonstration of wireless communication along with protocols would be done for the traffic signal control.

**Describe the solution you'd like...**
I would be using Node MCU for wireless communication along with led's, would be communicating to switch on/off led's

**Describe alternatives you've considered?**
NA

**Comment by prathimacode-hub** [comment]
Issue assigned to @SiddhantPawar03
