### ISSUE TITLE
Improving Go to top button

### ISSUE THREAD

**Issue by aaryahjolia** [prathimacode-hub/IoT-Spot#217]
---
Title: IoT-Spot Website
About: Improving Go to top button
Name: Aarya Ahjolia
Label: Feature Request'

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The Go to top button is aligned upwards, but it will look great if we put it in center of the circle.

**Describe the solution you'd like...**

To change the position of go to top button

**Additional context**

![GSSoC](https://user-images.githubusercontent.com/82600388/161589389-77fb8176-59c1-48c1-834f-8167550072a3.png)

**Comment by Ahad1317** [comment]
I WOULD LIKE TO WORK ON THIS ISSUE, CAN YOU PLEASE ASSIGN ME.

**Comment by Shaba1406** [comment]
I would like to fix this problem and align to it in a center so can you please assign me this

**Comment by its-abhishek** [comment]
can I work on this issue

**Comment by prathimacode-hub** [comment]
This is not necessary to be worked upon now. @its-abhishek
