### ISSUE TITLE
Adding a Favicon

### ISSUE THREAD

**Issue by aaryahjolia** [prathimacode-hub/IoT-Spot#218]
---
Title: IoT-Spot Website
About: Adding a Favicon
Name: Aarya Ahjolia
Label: Feature Request'

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

A website must have a favicon. I want to add a Favicon so it will look great to the user.

**Describe the solution you'd like...**

To Add a Favicon logo with 'I' as the text and red as background color as this color is also used in website so it will match the UI.

**Additional context**

![GSSoC](https://user-images.githubusercontent.com/82600388/166413992-00f0be4e-0a91-442d-a578-fee8f0113956.png)

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.

**Comment by Harsh3363** [comment]
Hey 
I can fix this please assign this to me

**Comment by its-abhishek** [comment]
I would like to work on this issue
