### ISSUE TITLE
Improving mobile view of website

### ISSUE THREAD

**Issue by aaryahjolia** [prathimacode-hub/IoT-Spot#219]
---
Title: IoT-Spot Website
About: Improving Mobile view with changes
Name: Aarya Ahjolia
Label: Feature Request'

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

There are lots of changes to be done in the mobile view. All the changes list is here and all the screenshots are also provided at end.
1. The hamburger color is white which is almost same as background color, making it difficult to see, so I want to make it black.
2. After opening hamburger menu, color of text are very less visible, so I will change it to white.
3. The text after tech stack should be center aligned.
4. The buttons at end should be center aligned so it will look perfect with current UI.

**Describe the solution you'd like...**

To make all the changes, to make mobile view a better UI for users.

**Additional context**

Image 1 : 
![GSSoC](https://user-images.githubusercontent.com/82600388/166414750-c8e9e83d-9998-458f-8af7-5e19d1e1d5ad.png)

Image 2  :
![GSSoC](https://user-images.githubusercontent.com/82600388/166414931-db39b091-b3e9-4388-9f01-9b975efbdc53.png)

Image 3 :
![GSSoC](https://user-images.githubusercontent.com/82600388/166415057-f2c9543d-4016-4b06-9936-dadd5540a0f8.png)

Image 4 :
![GSSoC](https://user-images.githubusercontent.com/82600388/166415155-b811bc09-1b5a-4223-a2d3-df10cc6f926a.png)

**Comment by prathimacode-hub** [comment]
Issue assigned to @aaryahjolia
