### ISSUE TITLE
Generate delay using 8051 timer.

### ISSUE THREAD

**Issue by VaibhavMogha** [prathimacode-hub/IoT-Spot#220]
---
Title: Generate delay using 8051 timers
About: I will be writing code to generate delay in C using 8051 timers.
Name: Vaibhav Mogha
Label: Feature Request
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Yes, Timers present in 8051 can help as timers or counters to count events. Using them we can create delay between two or more functions for there proper execution.

**Describe the solution you'd like...**

I will write a program for timer delay in 8051 microcontroller using led as an output port.

**Describe alternatives you've considered?**
NA

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned @VaibhavMogha

**Comment by VaibhavMogha** [comment]
Done.

**Comment by prathimacode-hub** [comment]
Why have you closed? @VaibhavMogha
