### ISSUE TITLE
Feature: Add CSS card hover effects in the inclusion part

### ISSUE THREAD

**Issue by MonalikaPatnaik** [prathimacode-hub/IoT-Spot#222]
---
Title: Add CSS card hover effects in the inclusion part
About:  I will be writing code to add css effects in inclusion part.
Name: Monalika Patnaik
Label: Feature Request
Assignee: ''

---

Define You:

- GSSOC Participant --Yes
-  Contributor--Yes

**Is your feature request related to a problem? Please describe.**

Yes, the inclusion part in the website looks static and can be improved by adding css card hover effects.

**Describe the solution you'd like...**
The inclusion part in the website can be improved by adding css card hover effects..

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

** ACTUAL**
![bug](https://user-images.githubusercontent.com/99353300/167454373-edd8740c-5a9d-4728-9543-2ab1b53fe17a.PNG)

** EXPECTED**
![Screenshot_2022-05-09-21-34-38-29_f9ee0578fe1cc94de7482bd41accb329](https://user-images.githubusercontent.com/99353300/167454511-6b764e89-3904-4e19-97dd-dfcb6a96b240.jpg)

**Comment by prathimacode-hub** [comment]
Issue assigned to @MonalikaPatnaik

**Comment by prathimacode-hub** [comment]
Progress update? Today is the last date of GSSoC. @MonalikaPatnaik

**Comment by MonalikaPatnaik** [comment]
> Progress update? Today is the last date of GSSoC. @MonalikaPatnaik

I have made the respective changes and you merged the pr as well (which fixes 226 )..kindly check..I
