### ISSUE TITLE
I2C Chat Application between Master and Slave

### ISSUE THREAD

**Issue by vaishnavighiradkar** [prathimacode-hub/IoT-Spot#223]
---
Title: I2C Chat Application between Master and Slave
About: Creating connection between two or more Arduino boards.
Name: vaishnavighiradkar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**

We'll get to know how to create connection between two or more arduino boards.

**Describe the solution you'd like...**

I'll be using two Arduino boards. One of them will act as Master and the other as slave.

**Approach to be followed (optional):**

The two boards will send messages two each other. Every time each board will act as transmitter and receiver.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vaishnavighiradkar
