### ISSUE TITLE
Motion Controlled Color Changer

### ISSUE THREAD

**Issue by shreya024** [prathimacode-hub/IoT-Spot#227]
Title: Motion Controlled Color Changer using Arduino
About: I'll be implementing the color changer using PIR, RGB and Buzzer
Name: Shreya Ghosh
Label: Feature Request
Assignee: ''

Define You:

[x] GSSOC Participant
[] Contributor
Describe the solution you'd like... I'll be implementing the color changer using PIR, RGB and Buzzer
file location: Minor scripts/Arduino

**Comment by shreya024** [comment]
@prathimacode-hub Kindly assign

**Comment by prathimacode-hub** [comment]
Issue assigned to @shreya024
