### ISSUE TITLE
Stopwatch Using Arduino

### ISSUE THREAD

**Issue by vaishnavighiradkar** [prathimacode-hub/IoT-Spot#228]
---
Title: Stopwatch using Arduino
About: Creating a stopwatch using arduino
Name: vaishnavighiradkar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**

We will be able to learn how to write code for displaying time in hours, minutes, and seconds. And how to control this using push buttons.

**Describe the solution you'd like...**
This program will show time in hours, minutes, and seconds on LCD. On pushing one of the pause or start buttons, the watch will act accordingly.

**Comment by prathimacode-hub** [comment]
Issue assigned to @vaishnavighiradkar
