### ISSUE TITLE
LCD interfacing with Atmega32

### ISSUE THREAD

**Issue by mohamedismail53** [prathimacode-hub/IoT-Spot#229]
Title: LCD interfacing with Atmega32
About: Creating a driver for LCD interfacing with atmega32 which required making a Dio driver
Name: Mohamed Ismail
Label: Feature Request
Assignee: ''

Define You:

 GSSOC22 Participant
 Contributor

Is your feature request related to a problem? Please describe.
Writing a string on an LCD or a number can be helpful with many embedded and IoT projects like calculators, stopwatches, and many more. So I'd provide a driver which can be used in any projects that need LCD it'll work like API.

Describe the solution you'd like...
The Driver will contain the functions in the following image:
![code-snapshot](https://user-images.githubusercontent.com/64151841/168493161-064c8f2b-8d7f-4e1a-9616-260aa4969ac5.png)

**Comment by prathimacode-hub** [comment]
Issue assigned to @mohamedismail53
