### ISSUE TITLE
IoT Spot : LCD Welcome Message using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#23]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to get welcome message on LCD screen using Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0), tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'SWOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by talkshrey** [comment]
Can you assign this issue to me? I have not been assigned a participation ID yet, how do I proceed?

**Comment by prathimacode-hub** [comment]
Yes, before assignment can you add out all the details mentioned above? Is your name not in participants sheet? @talkshrey

**Comment by talkshrey** [comment]
My name is in the participation sheet but the participation ID field is blank in it. Yeah I will provide all details in the PR. I am going to simulate the above code in tinkercad. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Ok, that's great. Approach and programming language? @talkshrey

**Comment by talkshrey** [comment]
Programming language: Embdded C
Approach: 1. Will set cursor to top left of lcd
                  2. Will use lcd.print command and type the message:
                          "Welcome to
                            IOT spot"
Is the message appropriate?

**Comment by prathimacode-hub** [comment]
Yes, absolutely. Go ahead. @talkshrey

**Comment by talkshrey** [comment]
![image](https://user-images.githubusercontent.com/74039736/145709743-7f1f4a91-bb80-4f5c-831e-cc0e63af403a.png)
Is this looking good?

**Comment by prathimacode-hub** [comment]
Yes, good. Does it has any alarm or it directly inputs the message? @talkshrey

**Comment by talkshrey** [comment]
> Yes, good. Does it has any alarm or it directly inputs the message? @talkshrey

It directly inputs the message, how do you suggest i go about with the alarm?

**Comment by prathimacode-hub** [comment]
This is all good for now, when we work on projects we can make it more advanced. Its fine for basic version of Welcome Message Code. @talkshrey

**Comment by prathimacode-hub** [comment]
Generally in such notification codes, they add buzzer to get a beep sound when notified. @talkshrey

**Comment by talkshrey** [comment]
> Generally in such notification codes, they add buzzer to get a beep sound when notified. @talkshrey

Yeah sure I'll try that out.

**Comment by prathimacode-hub** [comment]
All the best. @talkshrey

**Comment by talkshrey** [comment]
![image](https://user-images.githubusercontent.com/74039736/145711792-a333afe5-bae9-4fad-b0d9-058cc59ce663.png)
I have added a buzzer which will notify before the welcome message pops up

**Comment by prathimacode-hub** [comment]
Yes, go ahead. Is code ready? Check through the project structure, contributing guidelines and create a pull request using this [template](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/pullrequest_template.md). @talkshrey

**Comment by talkshrey** [comment]
> Yes, go ahead. Is code ready? Check through the project structure, contributing guidelines and create a pull request using this [template](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/pullrequest_template.md). @talkshrey

Yeah okay, code is ready sending a PR, pls check it out

**Comment by prathimacode-hub** [comment]
Can you share your participant ID? @talkshrey
