### ISSUE TITLE
Arduino Door Bell

### ISSUE THREAD

**Issue by DragonUncaged** [prathimacode-hub/IoT-Spot#231]
Title: A door Bell System.

Label: Feature Request
Assignee: ''DragonUncaged"

Define You:

[x] GSSOC Participant
[x] Contributor

Describe the solution you'd like... 
file location: IoT-Spot)/Arduino/

**Comment by DragonUncaged** [comment]
assign

**Comment by prathimacode-hub** [comment]
Issue assigned to @DragonUncaged. It should go into "IoT-Spot/Minor Scripts/Arduino"
