### ISSUE TITLE
IoT-Spot : Display Time on LCD using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#24]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to display time on LCD screen using Real Time Clock in Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0), tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'SWOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by rittikadeb** [comment]
Hi @prathimacode-hub, I am a GSSOC'22 contributor. I would like to work on this issue.

**Comment by SarthakSKumar** [comment]
Hey there. I am a GSSOC '22 Contributor. Can I please work on this issue?

**Comment by prathimacode-hub** [comment]
Yes,  let me know of your approach with this issue and tool you will use to get it assigned? @SarthakSKumar 

@rittikadeb Kindly choose issue wisely and contributors who express interest on FCFS basis starting today will be assigned. You can work on only 1 issue at a time.

**Comment by SarthakSKumar** [comment]
> Yes, let me know of your approach with this issue and tool you will use to get it assigned? @SarthakSKumar
> 
> @rittikadeb Kindly choose issue wisely and contributors who express interest on FCFS basis starting today will be assigned. You can work on only 1 issue at a time.



> Yes, let me know of your approach with this issue and tool you will use to get it assigned? @SarthakSKumar
> 
> @rittikadeb Kindly choose issue wisely and contributors who express interest on FCFS basis starting today will be assigned. You can work on only 1 issue at a time.

Thanks for your reply. I am planning on using DS3232 RTC Module, 16x2 LCD and a Uno Board. I have worked on this project before, and have the source for the same

**Comment by prathimacode-hub** [comment]
Issue assigned to @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Thank you!
