### ISSUE TITLE
Pressure Sensing using BMP280

### ISSUE THREAD

**Issue by piyusha2001** [prathimacode-hub/IoT-Spot#240]
We can sense pressure with the help of BMP280 sensor controlled via arduino microcontroller. The code will contain the logic of blinking LED after a certain pressure is reached . Please assign me this issue under GSSoC'22.

**Comment by prathimacode-hub** [comment]
I think this is already done. And always read contributing guidelines and README before you can create an issue. @piyusha2001

**Comment by piyusha2001** [comment]
@prathimacode-hub It is not done yet. I did check before creating an issue. Please verify once .

**Comment by prathimacode-hub** [comment]
Ok issue assigned to @piyusha2001

**Comment by prathimacode-hub** [comment]
Add the issue template here along with issue details as provided in the README and Contributing Guidelines. @piyusha2001

**Comment by piyusha2001** [comment]
---
Title: Pressure sensing using BMP280
About: We will get to know how to sense pressure using BMP280 module . To  see its working we will blink led after certain pressure is sensed.
Name: Piyusha Patil
Label: Feature Request
Assignee: Pratima Kadari

---

Define You:

- [x] GSSOC Participant 
- [ ] Contributor




**Is your feature request related to a problem? Please describe.**

Pressure sensing can be used in a lot of applications like to detect fire ,to calculate altitude or to deploy parachutes .

**Describe the solution you'd like...**

We will make use of BMP280 pressure sensor which will be controlled by arduino . We will make sure pressure is getting detected by connecting an led in a circuit .

**Comment by piyusha2001** [comment]
Can you add gssoc tags for the same?

> Ok issue assigned to @piyusha2001
