### ISSUE TITLE
Simon Says Game

### ISSUE THREAD

**Issue by shreya024** [prathimacode-hub/IoT-Spot#244]
Title: Simon Says Game using Arduino
About: I'll be implementing the Simon says game using LED,Switch and Buzzer
Name: Shreya Ghosh
Label: Feature Request
Assignee: ''

Define You:

[x] GSSOC Participant
[] Contributor
Describe the solution you'd like... I'll be implementing the game using PIR, RGB and Buzzer
file location: Minor scripts/Arduino

**Comment by shreya024** [comment]
@prathimacode-hub Kindly assign

**Comment by prathimacode-hub** [comment]
Issue assigned to @shreya024
