### ISSUE TITLE
Adding a tab icon to your website.

### ISSUE THREAD

**Issue by KiranAminPanjwani** [prathimacode-hub/IoT-Spot#249]
- I want to add a tab icon according to your website. 
- I am a GSSOC'22 participant, kindly assign this issue to me. Thank you.

**Comment by prathimacode-hub** [comment]
This issue is not valid as this is been worked upon without getting assigned. Moreover, issue you solved is negligible as it doesn't fit GSSoC criteria @KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
Okay no problem.
