### ISSUE TITLE
IoT-Spot : Color Detection on LCD using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#25]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to detect color and get it displayed on LCD screen with LED's using Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your  tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by CS50X-RGB** [comment]
Mam i am ROHAN CHATTERJEE from GSSOC '22 i would like to take this issue

**Comment by prathimacode-hub** [comment]
Can you explain your approach and tool you'll be taking up? @CS50X-RGB

**Comment by CS50X-RGB** [comment]
> Can you explain your approach and tool you'll be taking up? @CS50X-RGB 

Mam i don't know Arduino but i read some webpages came across to know about the tools part that it needed LCD display, sensor(for detecting the colour) and for the the approach part I am learning about.

**Comment by prathimacode-hub** [comment]
That sounds lively. You're free to explore as much as you could. Issue assigned. You can take up tinker cad for simulation purpose. Drop a message anytime up for queries @CS50X-RGB

**Comment by CS50X-RGB** [comment]
> That sounds lively. You're free to explore as much as you could. Issue assigned. You can take up tinker cad for simulation purpose. Drop a message anytime up for queries @CS50X-RGB 

Ok mam I am happy to get my first issue and if I get any queries I will let you know will thinkercad as I mentioned

**Comment by prathimacode-hub** [comment]
All the best. Yup. @CS50X-RGB
