### ISSUE TITLE
Random Dice Thrower using Arduino

### ISSUE THREAD

**Issue by shreya024** [prathimacode-hub/IoT-Spot#252]
Title: Random Dice Thrower using Arduino
About: I'll be implementing the Random Dice Thrower using 6 LEDs
Name: Shreya Ghosh
Label: Feature Request
Assignee: ''

Define You:

[x] GSSOC Participant
[] Contributor
Describe the solution you'd like... I'll be implementing the Random Dice Thrower using 6 LEDs and LCD
file location: Minor scripts/Arduino

**Comment by shreya024** [comment]
@prathimacode-hub Kindly assign

**Comment by prathimacode-hub** [comment]
Issue assigned to @shreya024
