### ISSUE TITLE
Want to improve CSS style of navigation bar and contact page

### ISSUE THREAD

**Issue by vedsom** [prathimacode-hub/IoT-Spot#253]
---
Title: Improvement of navigation option and contact page
About: want to improve the CSS part to make it more user friendly
Name: Abhishek Pandey
Label: Feature Request
Assignee: ''

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

Currently when we hover over the option it has black background.
And in contact page it has gray background with black color input which decreses the visisbility.
About and contact us button also doesn't have great effect which tells that button is clicked or not

**Describe the solution you'd like...**

Improve the CSS part of navigation tabs by matching website theme, which makes it more attractive.
Add animation, pressed affect over about  and contact us button which makes it more clear when button got pressed.
By changing te colors of contact us background and making send mail button more attractive.
Make Inclusion part little hoverable

**Comment by prathimacode-hub** [comment]
Could you add something more to this changes to validate as level 1 issue? @vedsom

**Comment by vedsom** [comment]
@prathimacode-hub mam I can make other buttons such as about and contact us to make the more attractive and can also improve the inclusion part

**Comment by vedsom** [comment]
Any other task which you want I can do it @prathimacode-hub mam

**Comment by prathimacode-hub** [comment]
Yes, please. We have less time so include these things whatever you had mentioned right now and revert PR by tomorrow at the earliest. Add these details in issue description as well about the other changes. Assigning this issue to you. @vedsom

**Comment by vedsom** [comment]
> Yes, please. We have less time so include these things whatever you had mentioned right now and revert PR by tomorrow at the earliest. Add these details in issue description as well about the other changes. Assigning this issue to you. @vedsom

Thanku so much @prathimacode-hub mam I will not disappoint you.
