### ISSUE TITLE
Remote Control Home

### ISSUE THREAD

**Issue by DragonUncaged** [prathimacode-hub/IoT-Spot#254]
Title: Random Dice Thrower using Arduino
About: I'll be implementing the Remote Control For Home
Name: DragonUncaged
Label: Feature Request
Assignee: ''

Define You:

- [x] GSSOC Participant
- [x] Contributor

Describe the solution you'd like... 
I'll be implementing the remote Control Home
file location: Minor scripts/Arduino

**Comment by prathimacode-hub** [comment]
Issue assigned to @DragonUncaged
