### ISSUE TITLE
Improvement in interface

### ISSUE THREAD

**Issue by Harsh3363** [prathimacode-hub/IoT-Spot#259]
There is more then required margin given in some places and also adding hover effect to the social media icons and subscribe button will be great 

![IMG_20220801_012507.jpg](https://user-images.githubusercontent.com/72756692/182042937-34445464-817d-4ccb-af3d-96c782b48c5a.jpg)

**Comment by Harsh3363** [comment]
Hii @prathimacode-hub  please assign this to me i would like to make the required changes

**Comment by prathimacode-hub** [comment]
Yes, but kindly go through the contributing guidelines. Add a issue template provide along with the details to get it assigned. @Harsh3363

**Comment by prathimacode-hub** [comment]
Are you a Social Summer Of Code participant? @Harsh3363

**Comment by Harsh3363** [comment]
> Yes, but kindly go through the contributing guidelines. Add a issue template provide along with the details to get it assigned. @Harsh3363 

Sure I will do that

**Comment by Harsh3363** [comment]
> Are you a Social Summer Of Code participant? @Harsh3363 

Yes
