### ISSUE TITLE
IoT-Spot : Traffic Lights Controller using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#26]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to control traffic lights using arduino

Sub Repo : /Minor Scripts/Arduino

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0), tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'SWOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by ritikalohia** [comment]
Assign me the task @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned to @ritikalohia

**Comment by ritikalohia** [comment]
## Related Issue 

- Info about the related issue 

- [ ] DWOC Participant  
- [x] SWOC Participant 
- [ ] Contributor

Closes: #26 number that will be closed through this PR

### Describe the changes you've made

I have made a new folder named traffic light controller, In which images, video , code and readme file are present. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been simulated on Tinkedcad, video is also in Images folder.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Image and video are uploaded in Images folder.
 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
 Original Block Diagram | Updated Block Diagram |
 Original Emulator Prototype Diagram | Updated Emulator Prototype Diagram |

**Comment by prathimacode-hub** [comment]
> ## Related Issue
> * Info about the related issue
> * [ ]  DWOC Participant
> * [x]  SWOC Participant
> * [ ]  Contributor
> 
> Closes: #26 number that will be closed through this PR
> 
> ### Describe the changes you've made
> I have made a new folder named traffic light controller, In which images, video , code and readme file are present.
> 
> ## Type of change
> What sort of change have you made:
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  This change requires a documentation update
> 
> ## How Has This Been Tested?
> It has been simulated on Tinkedcad, video is also in Images folder.
> 
> ## Checklist:
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly wherever it was hard to understand.
> * [x]  I have made corresponding changes to the documentation.
> * [x]  My changes generate no new warnings.
> * [x]  I have added tests that prove my fix is effective or that my feature works.
> * [x]  Any dependent changes have been merged and published in downstream modules.
> 
> ## Screenshots
> Image and video are uploaded in Images folder.
> 
> Original	Updated
> Original Screenshot	Updated Screenshot
> Original Block Diagram	Updated Block Diagram
> Original Emulator Prototype Diagram	Updated Emulator Prototype Diagram

You shouldn't add it in issues. You have to include in it in your commit message while creating PR. @ritikalohia
