### ISSUE TITLE
Improve UI of the Blog Page

### ISSUE THREAD

**Issue by Anjuli08** [prathimacode-hub/IoT-Spot#261]
The **Card** styling such as design and color does not impressive enough. I would like to change **card designs**, color and 
Improve **Navigation bar** of this section as well
![iot blog](https://user-images.githubusercontent.com/90701800/182911441-11569f3a-1741-49d9-a333-04ab00b56a27.png)

**Comment by Anjuli08** [comment]
---
Title: IoT-Spot
About: I want to Improve the UI of Blog section.
Name: Anjuli 
Label: Bug Report
Assignee: ''

---

Define You:

- [X] SSOC Participant  
- [X] Contributor




**Describe the Bug**
The present UI of the blog section is not impressive enough and the color palette also doesn't match the overall theme of the site.



**Steps to Reproduce**

Steps to reproduce the behavior:

1. Modifying the navigation bar.
2. Changing the Card design of all the blogs.
3. Applying more appropriate color theme.
4. Changing the size of buttons in footer. 


**Expected Behavior**
It will look a lot better and match with the theme of the Main Page of the site.


**Actual Behavior**

![iot blog (2)](https://user-images.githubusercontent.com/90701800/183230522-58716e6d-86cc-4c0e-8f4b-4445ce39ce7d.png)

![iot 2](https://user-images.githubusercontent.com/90701800/183230529-b33c520a-411b-4d9d-b70b-5d9ec62dc325.png)

**Comment by prathimacode-hub** [comment]
Issue assigned to @Anjuli08
