### ISSUE TITLE
Blink the LED using RaspberryPI

### ISSUE THREAD

**Issue by Harshil-Jani** [prathimacode-hub/IoT-Spot#263]
Basic task would be writing a program with RaspberryPI support to blink the LED. 
- Setting a specific time and blink the LED at some interval.
- You're Welcome to add any other creative features into the program as per your wish.

Note : There is no need to work on Hardware only, You can also work on the Simulation tools and libraries available.

**Comment by yk3066** [comment]
I would like to work on this issue as part of ssoc.
