### ISSUE TITLE
Detect the KeyPress on RaspberryPi

### ISSUE THREAD

**Issue by Harshil-Jani** [prathimacode-hub/IoT-Spot#264]
Basic task would be writing a program with RaspberryPI support to detect the keyPress on your machine. 
- You can try having one key assigned as an Exit key so, When you click it, The program gets terminate. 
- Detect other keys apart from the Exit key assigned. 
- You're Welcome to add any other creative features into the program as per your wish.

Note : There is no need to work on Hardware only, You can also work on the Simulation tools and libraries available.

**Comment by KshitizSachan** [comment]
Hi, Kshitiz here. I would like to work on this issue.
