### ISSUE TITLE
Fix Contact Us button

### ISSUE THREAD

**Issue by Harshil-Jani** [prathimacode-hub/IoT-Spot#266]
Title: IoT-Spot
About: Fix the Contact Us Button.
Name: @Harshil-Jani 
Label: Bug Report
Assignee: ''

### Define You:
- [ ] SSOC Participant
- [ ] Contributor
- [X] Mentor

### Describe the Bug
When you click the Contact Us button then It will go to projects section. 
But Instead of it, Make it to land on the Contact us section.

### Steps to Reproduce
- Click on the Contact Us button

![image](https://user-images.githubusercontent.com/79367883/183242973-566d0036-cec7-49d9-976e-030f7599111c.png)

**Comment by prjailani** [comment]
Hi sir, I am a SSOC contributor. Can you please assign me this issue. Thanks.

**Comment by Harshil-Jani** [comment]
Go Ahead !! @prjailani 🚀

**Comment by prjailani** [comment]
Hi sir, I fixed the issue. Please checkout my PR #268. Thanks.

**Comment by prjailani** [comment]
We can now close this issue

**Comment by prjailani** [comment]
I fixed it 20 days ago on PR #307  So we can close this issue now.
