### ISSUE TITLE
Add links to Project

### ISSUE THREAD

**Issue by Harshil-Jani** [prathimacode-hub/IoT-Spot#267]
Title: IoT-Spot
About: Add link to specific Directories.
Name: @Harshil-Jani 
Label: Bug Report
Assignee: ''

### Define You:
- [ ] SSOC Participant
- [ ] Contributor
- [X] Mentor

### Describe the Bug
(Refer ScreenShot) We only have the texts for the project currently in the projects section. Instead of that, If we can have links to specific directories then it would help in navigatiing easily from the site itself. 

### Steps to Reproduce
- Scroll the home page as per below ScreenShot
 
![image](https://user-images.githubusercontent.com/79367883/183243437-7dc39009-1e51-4492-9ae6-5a35121069ef.png)

**Comment by popcandy1x** [comment]
Hi sir, I am a SSOC contributor. Can you please assign me this issue.
