### ISSUE TITLE
Add Blink simulation and code for Atmega32 

### ISSUE THREAD

**Issue by khanasif786** [prathimacode-hub/IoT-Spot#271]
About: Add LED Blink code for Atemga32
Label: enhancement

Define You:
- [x] SSOC Participant
- [ ] Contributor
- [ ]  Mentor

Describe the Feature:
Adding a simple LED blink code feature in Atmega32A (latest version of atmega32) Microcontroller.

**Comment by Harshil-Jani** [comment]
Sure ! Go Ahead 🚀
