### ISSUE TITLE
Improving hover effect in Navbar [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [prathimacode-hub/IoT-Spot#279]
**Define You:**
- [x] SSOC Participant
- [ ] Contributor
 Mentor

**Describe the Bug**
Improving the hover effects and making "Let's Connect" button pointer

**Steps to Reproduce**
Hover on the site navbar

**Screenshot**
![image](https://user-images.githubusercontent.com/96040322/183708038-c094d7d9-5cfd-4c60-b5af-4eb6ae1a497e.png)

**Comment by ShivanshAr97** [comment]
Please assign it to me

**Comment by mdnazisharman2803** [comment]
@ShivanshAr97 you can work on

**Comment by mdnazisharman2803** [comment]
Done
