### ISSUE TITLE
IoT-Spot : Heart Beat Monitor using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#29]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to monitor the heart beat using Arduino

Sub Repo : /Minor Scripts/Arduino

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by vaishnavighiradkar** [comment]
I'm a contributor in GSSOC-22. I would like to work on this issue.

**Comment by prathimacode-hub** [comment]
Sure, go ahead with your work. Issue assigned @vaishnavighiradkar

**Comment by vaishnavighiradkar** [comment]
Ma'am, i'm unable to find the heartbeat sensor on tinkercad.

**Comment by vaishnavighiradkar** [comment]
![Screenshot (169)](https://user-images.githubusercontent.com/86549424/156580744-e926c47d-e19b-4e5f-a32d-3289573b04f8.png)

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub mam it is working now. 
While screen-recording simulation, the virtual terminal is not visible as it is another tab apart from proteus.

**Comment by prathimacode-hub** [comment]
Ok you add this screenshot and just the simulation of however it comes. @vaishnavighiradkar

**Comment by vaishnavighiradkar** [comment]
https://user-images.githubusercontent.com/86549424/156584570-8ffe7872-bc2a-4154-8f7b-676eb32fc75c.mp4

**Comment by vaishnavighiradkar** [comment]
is this okay @prathimacode-hub ?

**Comment by prathimacode-hub** [comment]
This is ok. For virtual terminal, you can take a screenshot and add it. @vaishnavighiradkar
