### ISSUE TITLE
Basic LED Blinking Using ESP8266

### ISSUE THREAD

**Issue by adithya-s-k** [prathimacode-hub/IoT-Spot#291]
---
Title: Basic LED Blinking Using ESP8266
About: writing a program with ESP8266 to blink the LED and set the time interval at which it blinks
Name: Adithya S Kolavi
Label: Feature Request
Assignee: 'adithya-s-k'

---

Define You:

- [x] SSOC Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
Blinking LED is the first project which helps set up the microcontroller, this will help check if everything is fine with the ESP8266

**Comment by prathimacode-hub** [comment]
Issue assigned to @adithya-s-k

**Comment by adithya-s-k** [comment]
@prathimacode-hub I have finished executing the code on my ESP8266(Hardware) and it works. Can you recommend any simulator software for the ES8266
