### ISSUE TITLE
Basic RGB LED Blinking Using ESP8266

### ISSUE THREAD

**Issue by Ankitdas05** [prathimacode-hub/IoT-Spot#294]
About: writing a program with ESP8266 to blink the RGB LED and set the time interval at which it blinks
Name: Ankit Das
Label: Feature Request
Assignee: 'Ankitdas05'

**Define You:**
- [x] SSOC Participant  
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
Blinking RGB LED is the project which helps set up the microcontroller, this will help check if everything is fine with the ESP8266

**Comment by adithya-s-k** [comment]
@snktshrma can you assign this issue to me?

**Comment by snktshrma** [comment]
@adithya-s-k! Done

**Comment by Anshul-13J** [comment]
I would like to work on this issue.
