### ISSUE TITLE
Style the Navbar

### ISSUE THREAD

**Issue by AnshuMishra01** [prathimacode-hub/IoT-Spot#300]
![Screenshot 2022-08-21 191748](https://user-images.githubusercontent.com/95041038/185794071-bd5b0d0f-5ae2-440c-ba6b-7790871f531d.png)

The styling of navbar is still incomplete

**Comment by prathimacode-hub** [comment]
Can you be elaborate? @AnshuMishra01

**Comment by d3mEnt0r** [comment]
Please assign this issue to me

**Comment by mdnazisharman2803** [comment]
> Please assign this issue to me

what changes will you make?

**Comment by d3mEnt0r** [comment]
I will style the navbar headings in proper line and make it responsive, so when the web page get smaller it opens in a drop down menu

**Comment by mdnazisharman2803** [comment]
@d3mEnt0r i am assigning you this, but make sure to add output screenshot, when i will feel the change is necessary i will consider the pr.

**Comment by d3mEnt0r** [comment]
ok sir
