### ISSUE TITLE
Basic LED Blinking Using ESP32

### ISSUE THREAD

**Issue by adithya-s-k** [prathimacode-hub/IoT-Spot#302]
---
Title: Basic LED Blinking Using ESP32
About: writing a program with ESP32 to blink the LED and set the time interval at which it blinks
Name: Adithya S Kolavi
Label: Feature Request
Assignee: 'adithya-s-k'

---

Define You:

- [x] SSOC Participant 
- [ ] Contributor

---

Is your feature request related to a problem? Please describe.
Blinking LED is the first project which helps set up the microcontroller, this will help check if everything is fine with the ESP32

**Comment by prathimacode-hub** [comment]
Issue assigned to @adithya-s-k
