### ISSUE TITLE
Converting the website into PWA [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [prathimacode-hub/IoT-Spot#303]
I would like to convert the website into a Progressive Web Application so that it can be installed in the user device or added to home screen and can also function offline.

**Comment by ShivanshAr97** [comment]
Please assign it to me!

**Comment by mdnazisharman2803** [comment]
i mean, what if i dont want to install web application, will i be still able to view website without installing it

**Comment by ShivanshAr97** [comment]
> @ShivanshAr97 will the current website be able to open or everyone will have to must install that web application ?

Yes yes
It will show such option
![image](https://user-images.githubusercontent.com/96040322/186424671-23c3983b-98d5-4c8f-8de2-cd42f5c9f71d.png)

Then give an option like:
![image](https://user-images.githubusercontent.com/96040322/186424993-8d0c5cdf-2d54-41bd-bdeb-0c05e9aca327.png)

For mobiles, it will show an option to add the site to home screen and after adding, it will be visible along with other android apps in your mobile phone

Also the site will be available offline

**Comment by mdnazisharman2803** [comment]
ok @ShivanshAr97  assigned

**Comment by Harshil-Jani** [comment]
@ShivanshAr97 Mention about the PWA Into the README. Since the PR is already merged and I don't want to revert it back to make things more complex, You can just create a new PR with PWA how to install it and how it helps all of these saying in a readme in few words.
