### ISSUE TITLE
IoT-Spot : Soil Moisture Detection using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#31]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to detect moisture of the soil using Arduino

Sub Repo : /Minor Scripts/Arduino

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub I'm GSSOC'22 Contributor, I would like to work on same issue, please assign me this task.

**Comment by prathimacode-hub** [comment]
Contribution starts from today so whoever expresses the interest right now will be assigned on FCFS basis. You can work on 1 issue at a time, so choose wisely. @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
Alright, So @prathimacode-hub  can I start working on this issue for now?

**Comment by prathimacode-hub** [comment]
Ok, so let me know your approach you would take up and tool you would use to get it assigned @SiddhantPawar03

**Comment by SiddhantPawar03** [comment]
I would work on Arduino UNO using tinkercad.
I would take a temperature sensor (LM35), would take analog values check for variety of conditions and displaying for same.
