### ISSUE TITLE
Social Icons not showing on website

### ISSUE THREAD

**Issue by prjailani** [prathimacode-hub/IoT-Spot#311]
---
About: Social Icons not showing on website
Name: Abdul Kader Jailani P R
Label: Bug Report
Assignee: 'prjailani'

---

Define You:

- [x] SSOC Participant  
- [ ] Contributor

**Describe the Bug**
Social Media icons not showing on website

**Expected Behavior**
Need to show social media icons in the buttons

**Actual Behavior**
Transparent background only showing on the website

**Screenshots/Block Diagram/Emulator Prototype Diagram**
![image](https://user-images.githubusercontent.com/76675034/189492566-b96a9500-e4f2-46fa-be5f-93842c39ccda.png)

**Comment by its-abhishek** [comment]
@prjailan ,I would like to work on this issue, can u plss assign me this issue under the HACKTOBERFEST'22
