### ISSUE TITLE
Updating ReadMe of ESP32 folder with information

### ISSUE THREAD

**Issue by SayuriYuto** [prathimacode-hub/IoT-Spot#328]
---
Title: Updating ReadMe of ESP32 folder with information
About: The ReadMe should contain information regarding the ESP32 board and how to install them.
Name: SayuriYuto
Label: Feature Request
Assignee: ''

---

Define You:

- ✅Hacktoberfest Participant 
- ✅Contributor

**Is your feature request related to a problem? Please describe.**

Many IOT developers wish to move forward from the world of Arduino into the vast eco system of EspressIf boards. But entering into an unknown grounds require some manual or a how to guide for easy passing. As ESP Boards are not pre installed nor are they pre configured in the Arduino IDE (which most of the arduino iot developers use), I wish to make a how to guide regarding the same.

**Describe the solution you'd like...**

I wish to provide a readme with infographics regarding ESP32 board like pin diagrams, specifications, documentations, etc. I also want to add a how to setup for esp32 in arduino IDE.

**Describe alternatives you've considered?**

Providing links to documentation, blogs, communities, where to buy, etc

To-do List:
[   ] Info of ESP
[   ] Pin diagrams
[   ] Specifications
[   ] Installation in arduino
[   ] Test run

**Comment by prathimacode-hub** [comment]
Issue assigned to @SayuriYuto
