### ISSUE TITLE
ESP32 Bluetooth based LED control(GPIO control)

### ISSUE THREAD

**Issue by adithya-s-k** [prathimacode-hub/IoT-Spot#332]
---
Title: ESP32 Bluetooth based LED control(GPIO control)
About: The esp32 not only has Wi-Fi connection but also has Bluetooth inbuilt
Name: Adithya S Kolavi
Label: Feature Request
Assignee: [adithya-s-k](https://github.com/adithya-s-k)

---

Define You:

- [x] Hacktoberfest Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**

The main feature of the code will be to take advantage of the Bluetooth functionality ESP32 has and use it to control the GPIO

**Comment by adithya-s-k** [comment]
@prathimacode-hub  can you assign this issue to me

**Comment by prathimacode-hub** [comment]
Issue assigned to @adithya-s-k
