### ISSUE TITLE
Updating ReadMe of ESP8266 folder with information

### ISSUE THREAD

**Issue by SayuriYuto** [prathimacode-hub/IoT-Spot#337]
Title: Updating ReadMe of ESP8266 folder with information
About: The ReadMe should contain information regarding the ESP8266 board and how to install them.
Name: SayuriYuto
Label: Feature Request

Define You:

✅Hacktoberfest Participant
✅Contributor

Is your feature request related to a problem? Please describe.

Many IOT developers wish to move forward from the world of Arduino into the vast eco system of EspressIf boards. But entering into an unknown grounds require some manual or a how to guide for easy passing. As ESP Boards are not pre installed nor are they pre configured in the Arduino IDE (which most of the arduino iot developers use), I wish to make a how to guide regarding the same.

Describe the solution you'd like...

I wish to provide a readme with infographics regarding ESP8266 board like pin diagrams, specifications, documentations, etc. I also want to add a how to setup for esp8266 in arduino IDE.

Describe alternatives you've considered?

Providing links to documentation, blogs, communities, where to buy, etc

To-do List:
- [x] Info of ESP
- [x] Pin diagrams
- [x] Specifications
- [x] Installation in arduino
- [x] Test run

**Comment by SayuriYuto** [comment]
Hey @prathimacode-hub can you please asssign this issue to me!!

**Comment by SayuriYuto** [comment]
Here is what I am planning to represent 
https://github.com/SayuriYuto/IoT-Spot/tree/esp8266info/ESP8266

**Comment by prathimacode-hub** [comment]
Issue assigned to @SayuriYuto
