### ISSUE TITLE
social icons are not  showing in a website

### ISSUE THREAD

**Issue by its-abhishek** [prathimacode-hub/IoT-Spot#338]
can I fix this issue under HACKTOBERFEST '22

**Comment by its-abhishek** [comment]
@prathimacode-hub can u assign me this issue under the HACKTOBERFEST '22

**Comment by prathimacode-hub** [comment]
Can you elaborate the issue? @its-abhishek

**Comment by its-abhishek** [comment]
![Screenshot 2022-10-30 191712](https://user-images.githubusercontent.com/100339461/198881993-e2040fa4-fa8e-495c-899b-441391e666f5.jpg)
@prathimacode-hub here the social icons are not working

**Comment by Shubham1450** [comment]
I can Fix this issue. Can you please assign this to me.
