### ISSUE TITLE
IoT-Spot : Alarm Clock using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#34]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to set the alarm and control the clock using Arduino

Sub Repo : /Minor Scripts/Arduino

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by talkshrey** [comment]
Can you assign this issue to me? Also how do you want me to do it?

**Comment by prathimacode-hub** [comment]
Ok, so this issue states that you set an alarm time using i/o pins and adding delays. It should buzz when time strikes. @talkshrey

**Comment by prathimacode-hub** [comment]
If you're ready to proceed, provide me your details to get it assigned. @talkshrey

**Comment by talkshrey** [comment]
Participant ID:918 
Participant name: SHREY PAREKH 
I would like to do this task

**Comment by prathimacode-hub** [comment]
Issue assigned to @talkshrey

**Comment by talkshrey** [comment]
Extremely sorry @prathimacode-hub my project ID is 41

**Comment by prathimacode-hub** [comment]
I need participant id only not project id @talkshrey

**Comment by talkshrey** [comment]
https://user-images.githubusercontent.com/74039736/148962107-b3a6ca1d-ea60-4d9b-8758-9dd8d65f38c7.mp4

Does this work?

**Comment by prathimacode-hub** [comment]
No, this is like creating a buzzer for some amount of time. Our project is alarm clock which would show like on. You have to set a time in HH:MM:SS format and when you input the time manually of when you want your alarm to ring, it should buzz then. @talkshrey

**Comment by prathimacode-hub** [comment]
Update please? @talkshrey

**Comment by talkshrey** [comment]
Sorry for the delay, I am not able to figure what tool can I use to measure real time

**Comment by prathimacode-hub** [comment]
Why what happen? Where are you stuck? @talkshrey

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub I'm GSSOC'22 Contributor, would be glad if you assign me this task.

**Comment by rittikadeb** [comment]
Hi @prathimacode-hub, I am a GSSOC'22 contributor. I would like to work on this issue.

**Comment by prathimacode-hub** [comment]
Contribution starts from today so whoever expresses the interest right now will be assigned on FCFS basis. @rittikadeb @SiddhantPawar03

**Comment by GnanambhalSvRam** [comment]
Mam, I would like to take up this issue to work on. I'm a GSSOC'22 contributor.

**Comment by prathimacode-hub** [comment]
Issue assigned to @GnanambhalSvRam. Let me know of the approach you would take up and tool you would use.

**Comment by GnanambhalSvRam** [comment]
> Issue assigned to @GnanambhalSvRam. Let me know of the approach you would take up and tool you would use.

Thank you ma'am. May I know how long do I have before informing you about the approach and the tool to be used?

**Comment by prathimacode-hub** [comment]
Right now without which issue can't be assigned. You don't have to elaborate, just add short intro and details asked for. @GnanambhalSvRam

**Comment by prathimacode-hub** [comment]
Its been 3 days and you haven't mentioned the approach after you got assigned. You can't hold it for so long else it will be kept open again for others to take up. @GnanambhalSvRam

**Comment by GnanambhalSvRam** [comment]
> Its been 3 days and you haven't mentioned the approach after you got assigned. You can't hold it for so long else it will be kept open again for others to take up. @GnanambhalSvRam

Apologies mam. I'm trying to figure it out. I'll be using Arduino and Wokwi Arduino Simulator along with few push buttons to specifically set the hours and minutes.

**Comment by prathimacode-hub** [comment]
Ok, so are you ready to take up this issue? @GnanambhalSvRam

**Comment by GnanambhalSvRam** [comment]
> Ok, so are you ready to take up this issue? @GnanambhalSvRam

Yes ma'am. I am ready to take this up.

**Comment by prathimacode-hub** [comment]
Ok, issue assigned to @GnanambhalSvRam

**Comment by prathimacode-hub** [comment]
Update please? @GnanambhalSvRam

**Comment by prathimacode-hub** [comment]
Update please? @GnanambhalSvRam

**Comment by SiddhantPawar03** [comment]
Hey, is anyone working on same issue?

**Comment by prathimacode-hub** [comment]
But there is no response from earlier contributor. You can go ahead with issue. @SiddhantPawar03
