### ISSUE TITLE
IoT-Spot : Basic RGB LED Blinking Using ESP8266

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#344]
Main task is all about writing a program with ESP8266 to blink the RGB LED and set the time interval at which it blinks

Blinking RGB LED is the project which helps set up the microcontroller, this will help check if everything is fine with the ESP8266

You're Welcome to add any other creative features into the program as per your wish.
Note : There is no need to work on Hardware only, You can also work on the Simulation tools and libraries available.

**Comment by mukundsolanki** [comment]
@prathimacode-hub Can you assign me this issue?

**Comment by prathimacode-hub** [comment]
Issue assigned @mukundsolanki

**Comment by mukundsolanki** [comment]
@prathimacode-hub I have created PR for the relevant issue and one more thing that you assigned me the issue but its not showing here...

![image](https://github.com/prathimacode-hub/IoT-Spot/assets/114515612/b14020a3-c824-4518-8574-fe61a9b49d8b)

Please review this PR

**Comment by mukundsolanki** [comment]
> @prathimacode-hub I have created PR for the relevant issue and one more thing that you assigned me the issue but its not showing here, please update this so it can be updated on the IWOC dashboard
> 
> ![image](https://private-user-images.githubusercontent.com/114515612/296441455-b14020a3-c824-4518-8574-fe61a9b49d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMzc1MDgsIm5iZiI6MTcwNTEzNzIwOCwicGF0aCI6Ii8xMTQ1MTU2MTIvMjk2NDQxNDU1LWIxNDAyMGEzLWM4MjQtNDUxOC04NTc0LWZlNjFhOWI0OWQ4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QwOTEzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGMyMzRhNWM5YzQ4MTUwODk1ZTNiOWRkNDFlMjg5MjE4NmJkOTFiNmQxZjg1ZTUxMzM3MDE1MGFlZTBiY2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BWn1qk6RMBs93yxT4zrF5qcm-_JBdNUbT0qIPL0qAdk)
> 
> Please review this PR

**Comment by prathimacode-hub** [comment]
Added label to the issue @mukundsolanki

**Comment by akash05pal** [comment]
> Main task is all about writing a program with ESP8266 to blink the RGB LED and set the time interval at which it blinks
> 
> Blinking RGB LED is the project which helps set up the microcontroller, this will help check if everything is fine with the ESP8266
> 
> You're Welcome to add any other creative features into the program as per your wish. Note : There is no need to work on Hardware only, You can also work on the Simulation tools and libraries available.

I can make LED blinking wireless from anywhere using BLYNK app. 
can u assign me this one??
@prathimacode-hub
