### ISSUE TITLE
IoT-Spot : Basic LED Blinking using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#4]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to activate the basic LED blinking using Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by NILESHSTARK** [comment]
Hello I am interested to fix this issue  Basic LED Blinking using Arduino

**Comment by prathimacode-hub** [comment]
Awesome, kindly provide the details asked to get it assigned. @NILESHSTARK

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub I'm GSSOC'22 Contributor, I would like to work on same issue.

**Comment by vaishnavighiradkar** [comment]
I'm a contributor in GSSOC-22.
Can you assign this issue to me?

**Comment by rk18venom** [comment]
Hello I am GSSOC 22 contributor.
I am interested to work on this issue.

**Comment by prathimacode-hub** [comment]
@rk18venom, provide the mentioned details to get it assigned.

For this issue, since the interest is expressed 2 days ago it might not count in the program. And @vaishnavighiradkar, you got 1 issue assigned to you right?

@SiddhantPawar03, you stand a chance to get this issue assigned if you're not working on an another issue. If so provide the mentioned details needed.

**Comment by silkie261001** [comment]
Hello I am GSSOC 22 contributor.
I am interested to work on this issue.

**Comment by prathimacode-hub** [comment]
@silkie261001, provide the mentioned details to get it assigned

**Comment by SarthakSKumar** [comment]
I'm willing to work on this issue.
Tool/Application: Arduino IDE, Fritzing, Embedded C Language
Components: Arduino Uno, LED, Jumper Wires/Connectors

**Comment by prathimacode-hub** [comment]
Great, issue assigned to @SarthakSKumar

**Comment by SarthakSKumar** [comment]
> Great, issue assigned to @SarthakSKumar

Thank you for the reply
