### ISSUE TITLE
projects on 8051 Microcontroller

### ISSUE THREAD

**Issue by nitishkumar07** [prathimacode-hub/IoT-Spot#52]
projects using assembly language and c programming in 8051 Microcontroller.
can I do it?

**Comment by prathimacode-hub** [comment]
8051 is allowed. Be specific with project title along with issue template provided [here](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/feature_request.md), the approach you would follow and what tool you would use up. Also mention yourself as GSSOC contributor @nitishkumar07

**Comment by ruhanirawal** [comment]
I would like to work on this issue since it's still open!

**Comment by prathimacode-hub** [comment]
Create a new issue with issue template provided mentioning the specific issue title along with details of what the issue is. @ruhanirawal
