### ISSUE TITLE
IoT Spot : Pressure Detection using Arduino

### ISSUE THREAD

**Issue by Jyo561** [prathimacode-hub/IoT-Spot#53]
Title:Pressure detection using Arduino    
                   
About:I will use an arduino, force sensor and multimeter to bring this to life     

Name:Jyotiraditya Kuanar

Label:                                 

[x]GSSOC Participant
[] SWOC Participant
[] Contributor

Will be using c++ as the code and make user of Force sensor, Multimeter, battery and arduino to bring it into effect

**Comment by GnanambhalSvRam** [comment]
Hi ma'am! Can you please assign me to this issue?

**Comment by prathimacode-hub** [comment]
Kindly follow the issue template provided [here](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/feature_request.md) along with the approach you would take up and tool you would use to get it assigned.  @Jyo561 

This issue is created by a contributor. You can come up with an own issue or choose up from existing issues by expressing interest by mentioning  your approach and tool you would use. You can work on only 1 issue at a time. @GnanambhalSvRam

**Comment by Jyo561** [comment]
@prathimacode-hub maam its done can now i get it assigned

**Comment by prathimacode-hub** [comment]
Ok issue assigned. You can proceed. @Jyo561

**Comment by prathimacode-hub** [comment]
Update please? @Jyo561

**Comment by prathimacode-hub** [comment]
Update please? @Jyo561

**Comment by Jyo561** [comment]
Mam Sorry but i am unable to complete it as my laptop has malfunctioned and had to send it to a repair show currently commenting from my mobile phone via Github app . SO if you can extend it till 10th then it would be great or let me close this request  so that i will renew my issue anagain or assign me an issue for which i can work for.

**Comment by vaishnavighiradkar** [comment]
@prathimacode-hub If this is still open, can you assign this issue to me? I'll be using tinkercad for circuit building and simulation. I'll consider a fixed area and measure force by force sensor. By doing this i can calculate Pressure(Force/Area). And It will be printed on LCD screen or serial monitor.

**Comment by prathimacode-hub** [comment]
Ok @Jyo561 no worries you can choose an issue whenever you could contribute. For now, i will assign it to next person on queue. 

Ample number of issues coming, so stay tuned.

Sure, @vaishnavighiradkar, issue is assigned to you.
