### ISSUE TITLE
Remote Control Car Circuit Using Arduino on TinkerCad

### ISSUE THREAD

**Issue by rk18venom** [prathimacode-hub/IoT-Spot#55]
I am GSSOC 22 Contributor. I have made this circuit want to add it in your repository.

**Comment by prathimacode-hub** [comment]
Kindly follow the issue template provided [here](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/feature_request.md) along with the approach you would take up and tool you would use to get it assigned. @rk18venom

**Comment by rk18venom** [comment]
Hello, so I am using TinkerCad for making the circuit in which i am using motor driver L239D, Arduino UNO R3, two motors, and breadborad.
So when we input F from serial monitor which means move forward so both motor will rotate in clockwise direction and in the same way we will give input like B (Backward), Left(L), Right(R) and S(Stop) by changing the direction of rotation of motors.

**Comment by prathimacode-hub** [comment]
Also add the same details using the [issue template](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/feature_request.md) provided for getting it assigned. @rk18venom

**Comment by rk18venom** [comment]
Title: Remote Control Car Circuit Using Arduino on TinkerCad #55
About: We will give the command to the RC car for moving forward, backward, etc.
Name: Rahul Kashyap
Label: Feature Request

Define You:

 GSSOC 22 Contributor

I have not talked with the program manager before creating this issue. So, I want to add this file of RC Car Circuit Simulation to this repo.


Approach to be followed (optional):

Forward(F) -- Car will move in forwarding direction.
Backward(B) -- Car will move in the backward direction.
Left(L) -- Car will move in the left direction.
Right(R) -- Car will move in the right direction.
Stop(S) -- Car will stop.


Requirements:
Arduino Uno R3
2 Motors
Tinkercad
 L239D Motor Driver
 Breadboard

**Comment by prathimacode-hub** [comment]
Issue assigned to @rk18venom
