### ISSUE TITLE
Design better logo

### ISSUE THREAD

**Issue by ShambhaviDixit09** [prathimacode-hub/IoT-Spot#59]
Hello,
I am a GSSOC 2022 participant and I would like to make a better logo for this project to make it display on the navbar. So, i would request you to assign me this work

**Comment by Ankit62042** [comment]
I want to work on this issue

**Comment by prathimacode-hub** [comment]
Interesting choice of the first issue. Go ahead. All the best. @ShambhaviDixit09

**Comment by prathimacode-hub** [comment]
@Ankit62042 Issue assigned on FCFS basis and create your own issue or express interesting in existing open issues according to what it is right now.

**Comment by prathimacode-hub** [comment]
Update please? @ShambhaviDixit09

**Comment by prathimacode-hub** [comment]
Update please? @ShambhaviDixit09

**Comment by prathimacode-hub** [comment]
Update Progress? Today is the last date for GSSoC. @ShambhaviDixit09
