### ISSUE TITLE
Social media icons are not aligned correctly

### ISSUE THREAD

**Issue by Anirban-1490** [prathimacode-hub/IoT-Spot#63]
Title: Social media icons are not aligned correctly
About: position issue of social media icons
Name: Anirban Pratihar
Label: Bug Report
Assignee: ''

---

Define You:

- [x] GSSOC Participant  
- [x] Contributor

 YES

**Describe the Bug**

social media icons in contact us page is not aligned correctly 

**Expected Behavior**

![Opera Snapshot_2022-03-02_154420_prathimacode-hub github io](https://user-images.githubusercontent.com/82874704/156342328-3756ce2a-5f34-42f1-bdc1-7408b55ef9c8.png)

**Actual Behavior**

![Opera Snapshot_2022-03-02_154520_prathimacode-hub github io](https://user-images.githubusercontent.com/82874704/156342370-d2ffc171-36d8-40ad-8be6-39aa1630c7d9.png)

@prathimacode-hub please assign this issue to me under GSSOC22

**Comment by silkie261001** [comment]
Hello I am GSSOC 22 contributor.
I am interested to work on this issue.

**Comment by Anirban-1490** [comment]
> Sure, I will assign this issue. But use issue template provided to add what the issue is about so that I can assign it to you. @Anirban-1490
> 
> Comment on issues created by me if it's open but not on issues created by contributors and select 1 issue you would like to, then express interest by providing the mentioned details to get it assigned. @silkie261001

done .check it

**Comment by prathimacode-hub** [comment]
Issue assigned to @Anirban-1490. Go ahead

**Comment by Anirban-1490** [comment]
> Issue assigned to @Anirban-1490. Go ahead

thank you :)
