### ISSUE TITLE
While hovering on about and contact icon not changing their colours

### ISSUE THREAD

**Issue by silkie261001** [prathimacode-hub/IoT-Spot#64]

**Comment by silkie261001** [comment]
Hello I am GSSOC 22 contributor.
I am interested to work on this issue.

**Comment by prathimacode-hub** [comment]
Use [issue template](https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/bug_report.md) given and add what the issue is about and your approach you would follow along with screenshot to get it assigned. @silkie261001

**Comment by Khushi25pandey** [comment]
I would like to work on the issue. Please assign it to me @prathimacode-hub

**Comment by prathimacode-hub** [comment]
This issue is created by other contributor. Can you create a new issue from your behalf using the issue template provided along with mentioned details to get it assigned. @Khushi25pandey

**Comment by Khushi25pandey** [comment]
Ya sure! I would try definitely @prathimacode-hub
