### ISSUE TITLE
Image and IOT-DESIGN logo stack on each other for medium screens, contact redesign

### ISSUE THREAD

**Issue by vedsom** [prathimacode-hub/IoT-Spot#69]
Title: Image and IOT-DESIGN logo stack on each other for medium screens and some changes to contact section
About: Create a report to help us improve.
Name: Abhishek Pandey
Label: Bug Report
Assignee: ''

Define You:

- [x] GSSOC Participant  

- [x] Contributor

**Describe the Bug**

1. If we reduce the size of screen to medium one than the image and the IOT-DESIGN logo above contact and about get stack over each other, which makes this page not responsive for medium screens.
2. Second thing I want to change is contact section, due to its color its not so much attractive, I want to add some borders and good css styles over it, make it hover too.

**Steps to Reproduce**

1. Apply some media conditions which will make it responsive for medium screens.
2. Add borders, make changes to color of input part etc

**Expected Behavior**

If we reduce the size of screen to medium one then also image and iot-design logo do not stack over each other

**Actual Behavior**

They stack over each other if we reduce the screen size

**Screenshots/Block Diagram/Emulator Prototype Diagram**

![IOT-Spot - Google Chrome 02-03-2022 19_05_41](https://user-images.githubusercontent.com/96954912/156376409-ffa394b9-ca78-4f50-80e8-154f4e707b02.png)

**Additional Details* 

just try to resize the screen

**Comment by prathimacode-hub** [comment]
Update please? @vedsom

**Comment by prathimacode-hub** [comment]
Update please? @vedsom

**Comment by vedsom** [comment]
> Update please? @vedsom

mam i will complete it till tonight, sorry for being late i have my end sem exams.

**Comment by prathimacode-hub** [comment]
Ok. @vedsom

**Comment by vedsom** [comment]
@prathimacode-hub  mam i have solved the issue , please look into it and merge it. As tomorrow is last date of contributing thankyou.

**Comment by prathimacode-hub** [comment]
Ok. @vedsom
