### ISSUE TITLE
IoT-Spot : LED Brightness Control using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#7]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to control LED brightness with Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by SiddhantPawar03** [comment]
@prathimacode-hub I'm GSSOC'22 Contributor, would be glad if you assign me this task.

**Comment by rk18venom** [comment]
@prathimacode-hub I am GSSOC 22 Contributor, I would to like to contribute in this issue. Can you assign me this issue?

**Comment by prathimacode-hub** [comment]
@SiddhantPawar03 @rk18venom You can work on only one issue at a time, so choose the issue wisely

**Comment by nitishkumar07** [comment]
I am GSSOC Contributor
I would like to work on this issue
I use tinkercad for simulation
can you assign me this issue? @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Yes, issue assigned. What's the approach? @nitishkumar07

**Comment by nitishkumar07** [comment]
I use arduino uno r3, Led, and register.
change brightness form 0 to 255 by using loop
with delay 20
loop runs till it reaches 255 
add another loop to reduce brightness till 0.
