### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ZeyadTarekk** [prathimacode-hub/IoT-Spot#72]
---
Title: Fix a bug in the projects section
Name: Zeyad Tarek
Label: Bug Report
Assignee: ''

---

I'm a GSSOC Participant  

**Describe the Bug**
In the projects section the icons are going up here is screenshot for the bug
https://drive.google.com/file/d/1__tQh9OYNdhqEK_1jltXGGKCUPAas4Tf/view?usp=sharing

**Steps to Reproduce**

1. I can fix it and here is a screenshot after fixing it https://drive.google.com/file/d/1fyK6HGB5hRZw51SlaZu7BaA54juzY-MI/view?usp=sharing

**Expected Behavior**

The icons are in the middle.

**Actual Behavior**

The icons aren't in their right place

**Comment by abhisheks008** [comment]
This bug is already reported by other contributor and is fixed by him/her. Try to find out some other area to contribute @ZeyadTarekk

**Comment by prathimacode-hub** [comment]
You can just edit out here with new issue. @ZeyadTarekk
