### ISSUE TITLE
To detect smoke level using gas sensor

### ISSUE THREAD

**Issue by vaishnavighiradkar** [prathimacode-hub/IoT-Spot#77]
With this issue, the readers will get to know how to read data from gas sensors using Arduino.

Domain
Internet Of Things

**Comment by prathimacode-hub** [comment]
Smoke detection is done already if this is what you meant. https://github.com/prathimacode-hub/IoT-Spot/tree/main/Arduino/Smoke%20Detection%20Using%20Arduino @vaishnavighiradkar
