### ISSUE TITLE
Add animation effect to IoT landing image on hovering

### ISSUE THREAD

**Issue by Sreemoyee26** [prathimacode-hub/IoT-Spot#78]
---
Title: Add animation effect to IoT landing image on hovering
About: making the image have a animation on hovering like it moves on moving cursor over it.
Name: Sreemoyee Sadhukhan
Label: Feature Request
---

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

-  The IoT image in the home page is simple and static. It is not looking too good enough.

**Describe the solution you'd like...**

-  I had a suggestion of making it have a animation on hovering like it moves on moving cursor over it.

**Approach to be followed (optional):**

- Using JS to add tilting and moving effects to image on moving mouse over it on hovering.

**Screenshot**

![Screenshot (657)](https://user-images.githubusercontent.com/77785024/156569159-5cd57a79-ccae-4b63-b7b5-d3d01e112214.png)

**Comment by Sreemoyee26** [comment]
I am a GSSOC' 2022 Contributor

**Comment by prathimacode-hub** [comment]
Yup, sure. Can you use issue template provided with the same details you had mentioned right now along with approach you would follow to get it assigned. @Sreemoyee26

**Comment by Sreemoyee26** [comment]
> Yup, sure. Can you use issue template provided with the same details you had mentioned right now along with approach you would follow to get it assigned. @Sreemoyee26

updated as per the template.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Sreemoyee26
