### ISSUE TITLE
UI enhancement on Blog page 

### ISSUE THREAD

**Issue by ABHID10** [prathimacode-hub/IoT-Spot#82]
Changing UI of Blog Page https://prathimacode-hub.github.io/IoT-Spot/assets/blog.html
Tech Stack - 
- [x] HTML
- [x] CSS
- [x] Javascript

GSSoC-22

**Comment by prathimacode-hub** [comment]
This is a good enhancement. Can you include the issue template provided along with mentioning the issue details and approach you would follow to get it assigned? @ABHID10

**Comment by prathimacode-hub** [comment]
Go ahead. Task assigned to @Siddhi-Mundada
