### ISSUE TITLE
Improvement in README.md file

### ISSUE THREAD

**Issue by rv602** [prathimacode-hub/IoT-Spot#83]
hey @prathimacode-hub ,

In the README.md file, the hyperlinks attached open the links in the same tab which may cause a bit of inconvenience as contributors would like to have the repo tab and prefer the other links in a new tab.
Also, there were a few reference links/repos, having this hyperlinking issue.
I would furthermore like to put all the reference site and repos in a tabular manner which will make the README.md file look much neater.

I will fix the hyperlinking issue by adding a target="_blank" in the anchor tag attribute and use the relevant html table tags for making the content in a tabular form.
 
Hoping to get assigned to work on this issue, as it would add a lot of convenience to the contributors.

**Comment by prathimacode-hub** [comment]
This add-on would be great. But it won't be labelled a GSSoC tag. If that's ok for you, let me know so that I can assign @rv602

**Comment by rv602** [comment]
yes @prathimacode-hub that's okay by me, just feel good to notice these things and get these ideas 😃.
You may assign this to me.

**Comment by prathimacode-hub** [comment]
Glad to know. Go ahead. @rv602

**Comment by prathimacode-hub** [comment]
Update please? @rv602

**Comment by prathimacode-hub** [comment]
Update please? @rv602

**Comment by rv602** [comment]
sorry for the delay @prathimacode-hub. I was shifting my house hence got occupied in the shifting process. I'll complete it within 2-3 days.
Sorry for the delay.
