### ISSUE TITLE
Website is not responsive

### ISSUE THREAD

**Issue by simransaini212** [prathimacode-hub/IoT-Spot#84]
Hi, Simran Saini this side GSSOC22 contributor
I have checked the website, styling fonts and everything is awesome but there is no responsiveness in your website. The Single picture covers all the stuff as we minimise the page size.
You can assign me this issue so that I can fix this.

**Comment by prathimacode-hub** [comment]
Yes, please include the issue template provided along with issue details and approach you would follow to get it assigned. @simransaini212
