### ISSUE TITLE
wrong hyperlink in README.md

### ISSUE THREAD

**Issue by itsAftabAlam** [prathimacode-hub/IoT-Spot#86]
i hope the below mentioned PR fixes this. please review

**Comment by prathimacode-hub** [comment]
Hmm, but you shouldn't create a PR without getting an issue assigned. And this is quite a low level change, and as we have only 3 levels for GSSoC, the add-on won't count under this program. If it's ok for you I can assign it. @itsAftabAlam

**Comment by itsAftabAlam** [comment]
@prathimacode-hub  I apologize for creating PR before getting it assigned. I look for to make more relevant issues.

**Comment by prathimacode-hub** [comment]
Sure, Its no late. You can now also edit up this issue with relevant one and get it assigned. This repo encourages beginners to start their journey. So don't hesitate to start yours. No apologies needed. This is how you learn. @itsAftabAlam
