### ISSUE TITLE
Introduction to 8051 MicroController

### ISSUE THREAD

**Issue by ruhanirawal** [prathimacode-hub/IoT-Spot#88]
https://github.com/prathimacode-hub/IoT-Spot/blob/main/.github/issue_template/feature_request.md

Title: 8051 Micrcontroller
Name: Ruhani Rawal
Define yourself:
- [x] GSSOC participant 
Contributor

Approach/Solution: 
I'll be updating the README file for the 8051 microcontroller. I'll be including the History, Architecture, Applications, Programming basics using Assembly Language.

**Comment by prathimacode-hub** [comment]
@ruhanirawal, this shows addition of 4 projects. Be curative of the issue title. You can work on one after the other. Go through the contributing guidelines and README file of the project for structure. You have issue template provided. Include it here along with the issue details and approach you would follow for that specific issue title. And you can work on only 1 issue at a time. Good upfront for initiating 8051 amidst arduino.

**Comment by prathimacode-hub** [comment]
Include why its used as well. Issue assigned to @ruhanirawal

**Comment by prathimacode-hub** [comment]
Update please? @ruhanirawal

**Comment by prathimacode-hub** [comment]
Update please? @ruhanirawal

**Comment by ruhanirawal** [comment]
> Update please? @ruhanirawal 

Almost done@prathimacode-hub

**Comment by SiddhantPawar03** [comment]
Hey, is anyone still working on same issue?

**Comment by prathimacode-hub** [comment]
No one, You can go ahead by creating a new issue with this title. @SiddhantPawar03
