### ISSUE TITLE
IoT-Spot : Reading Sensor Data using Arduino

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/IoT-Spot#9]
### Description

Welcome to 'IoT-Spot', good to see you here.

With this issue, the readers will get to know on how to read sensors data using Arduino

Sub Repo : Arduino Scripts

To get assigned to this issue, add your tool/application you would like to choose. the programming language and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Simulation is must. Block Diagram is Optional.

- README should be concise and elaborate with detailed information on the process.

This issue is only for 'GSSOC' contributors

### Domain

Internet Of Things

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/prathimacode-hub/IoT-Spot/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by rittikadeb** [comment]
Hi @prathimacode-hub, I am a GSSOC'22 contributor. I would like to work on this issue. Can you please specify about the type of sensor?

**Comment by prathimacode-hub** [comment]
Kindly express your interest today along with details mentioned to count under this open source program and get it assigned. @rittikadeb

**Comment by rk18venom** [comment]
---
Title: Reading Sensor Data using Arduino #9
About: Sensing the distance of object using ultrasonic sensor and printing it on serial monitor.
Name: Rahul Kashyap
Label: New Project
Assignee: rk18venom

---

Define You:

- [x] GSSOC Participant 
- [x] Contributor




**Is your feature request related to a problem? Please describe.**



**Describe the solution you'd like...**



**Describe alternatives you've considered?**



**Approach to be followed (optional):**


I am using TinkerCad for making the circuit in which I am using ultrasonic sensor and Arduino Uno r3 and sensing the distance of the object and printing it on the serial monitor.
**Additional context**

**Comment by vaishnavighiradkar** [comment]
I have solved this issue using gas sensor , 3 led lights (red, green, yellow) to show the level of gas intensity and a buzzer on tinkercad. . At High intensity of gas , buzzer buzzes. It is working properly. please assign this issue to me

**Comment by prathimacode-hub** [comment]
Sorry, you missed the assignment by few mins. @vaishnavighiradkar
