### ISSUE TITLE
Automated Hand Sanitizer Dispenser

### ISSUE THREAD

**Issue by SiddhantPawar03** [prathimacode-hub/IoT-Spot#90]
---
Title: Automated Hand Sanitizer Dispenser
About: Useful in ongoing pandemic
Name: Siddhant Pawar
Label: Feature Request
Assignee: ''

---

Define You:

- [X] GSSOC Participant 
- [X] Contributor

**Is your feature request related to a problem? Please describe.**
<br>Yes, the problem is very much related in ongoing pandemic i.e Covid-19 as avoiding touching of hands is necessity nowadays, in order to do so would be working on same project.

**Describe the solution you'd like...**
<br>The solution would be using ultrasonic distance sensor which would detect the presence of person and would dispense the sanitizer as per the requirement.

**Describe alternatives you've considered?**
NA

**Approach to be followed (optional):**
Earlier Mentioned

**Comment by prathimacode-hub** [comment]
Issue assigned to @SiddhantPawar03
