### ISSUE TITLE
DC Motor Interfacing using 8051 Microcontroller

### ISSUE THREAD

**Issue by nitishkumar07** [prathimacode-hub/IoT-Spot#91]
I am a GSSOC'22 contributor.

I want to do project on DC Motor.
rotation of Dc Motor in clockwise and anticlockwise

Use of tools: Proteus 8 for simulation, keil for writing program.
I use c programming
components: AT89C51 microcontroller, DC Motor, ICL29D,switches.

**Comment by prathimacode-hub** [comment]
Can you add the issue template provided and include these details to get it assigned. @nitishkumar07

**Comment by nitishkumar07** [comment]
---
Title: DC Motor Interfacing using 8051 Microcontroller
About: rotation of dc motor in clockwise and anti clickwise direction
 Name: Nitishkumar J G
Label: GSSOC'2022 
Assignee: ''

---

Define You:

- [ X ] GSSOC Participant 
- [ X ] Contributor




**Is your feature request related to a problem? Please describe.**
no, it helps in learning dc motor operation and 8051 microcontroller


**Describe the solution you'd like...**


Use of tools: Proteus 8 for simulation, keil for writing program.
I use c programming
components: AT89C51 microcontroller, DC Motor, ICL29D,switches.

**Describe alternatives you've considered?**



**Approach to be followed (optional):**



**Additional context**

**Comment by prathimacode-hub** [comment]
Issue assigned to @nitishkumar07. Go ahead.

**Comment by Bhupesh9521** [comment]
L293D Motor driver
