### ISSUE TITLE
Design and Code Blog page 

### ISSUE THREAD

**Issue by SachinMittal1766** [prathimacode-hub/IoT-Spot#95]
Hi, Blog page is not designed and coded. So I want to work on this. Can you @prathimacode-hub please assign it to me.
I am attaching a UI design below:
![IoT-Spot](https://user-images.githubusercontent.com/82721772/156886117-7370c0c1-9097-466d-862a-005f6f7b2b87.png)

**Comment by prathimacode-hub** [comment]
Yes, sure. But kindly add the issue template along with issue details mentioned and approach to get it assigned. @SachinMittal1766

**Comment by SachinMittal1766** [comment]
---
Title: IOT-Spot
About: Adding blog page
Name: Sachin Mittal
Label: Feature Request
Assignee: ''

---

Define You:

- [ ] GSSOC Participant 
- [ ] Contributor




**Is your feature request related to a problem? Please describe.**


Blog page is not made. 

**Describe the solution you'd like...**


I have added the UI of page. So I will make the page similar to it.
![IoT-Spot](https://user-images.githubusercontent.com/82721772/156888302-d07929b6-2c45-448c-95cf-cb2b3568602e.png)

**Approach to be followed (optional):**


Once you accept UI. I will start coding it & make it responsive also. 
In 3-4 days, I will complete my work

**Comment by prathimacode-hub** [comment]
Issue assigned to @SachinMittal1766

**Comment by prathimacode-hub** [comment]
Update please? @SachinMittal1766

**Comment by prathimacode-hub** [comment]
Update please? @SachinMittal1766

**Comment by SachinMittal1766** [comment]
I have made Webpage & working on responsiveness. Will make PR by EOD.
