### ISSUE TITLE
Arduino Based Home Automation System

### ISSUE THREAD

**Issue by rittikadeb** [prathimacode-hub/IoT-Spot#96]
Title: Arduino Home Automation System
Name: Rittika Deb
Label: New project

Define You:

- [x] GSSOC Participant 
- [x] Contributor

**Describe the solution you'd like...**

This project deals with Home Automation system using Arduino UNO as the microcontroller. It will control the working of bulbs and fans according to the temperature of the surrounding. 

**Approach to be followed:**

I will be using Arduino UNO, DC motors  which will act as the fans, bulbs , temperature sensor etc. in this project and simulation will be done in Tinkercad.

**Comment by prathimacode-hub** [comment]
Issue assigned to @rittikadeb

**Comment by prathimacode-hub** [comment]
Update please? @rittikadeb

**Comment by prathimacode-hub** [comment]
Update please? @rittikadeb

**Comment by debrittika** [comment]
Coding is left. I have designed the circuit on Tinkercad

**Comment by rittikadeb** [comment]
Coding is left. I have designed the circuit.
